### ISSUE TITLE
Unix Shell experience

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#10]
In working with the Unix shell, what did you find the most fun? least fun?

**Comment by yaaminiv** [comment]
I really liked being able to manipulate and organize files from the terminal. When working with large data sets, it can be cumbersome to physically drag and drop several files to organize them. I thought using pipes was really efficient as well. I didn't like creating new text files on the terminal's editor. I had some problems trying to write out the data to the disk. I also can't really see why using the terminal to create files is "better" than creating a file normally.

**Comment by mfisher5** [comment]
_most fun_ - I also liked being able to manipulate files from inside the terminal, particularly being able to read the first few lines, sorting file contents, word and line counts, etc. I have already had my computer freeze from opening large data files, so I think this will be the most useful. 
_least fun_\- I am not yet entirely comfortable with how some of the commands interact, so I have trouble visualizing the final output of some of the pipelines; until I become more familiar with the code, I would be hesitant to do a large amount of file editing from the command line.

**Comment by aspanjer** [comment]
**most fun** - being able to connect scripts to run an analysis through a pipeline seems extremely useful. I also really like the ability to use tab for auto completing file names within a directory and using '*' and '?' for calling-on multiple files with only small differences in their name.

**least fun** - The risk of deleting files with a few misplaced key strokes worries me, but maybe this isn't too much of an issue in practice. I could use some advice on automating file back-ups to prevent this from being a problem.

**Comment by laurahspencer** [comment]
Most fun: not using a mouse to point/click (that's annoyingly labor intensive); becoming more familiar with (very) simple commands, e.g. moving within the directory. 
Least fun: not being able to visually see multiple folders/files at once; unless you check for something you won't see that it is there or missing, which makes me nervous. The remove function is terrifying!

**Comment by MeganEDuffy** [comment]
**_most fun_** : learning how to use pipes, especially more than two at a time. So efficient! I want to learn about other processes that I can use to manipulate, sort, and create files.

**_least fun_** : using Nano was fine, but when I tried to make a file with Sublime 2 from the terminal using the CLI (command line interface) subl I was unsuccessful. I tried to make a symlink to subl using the instructions [here](http://www.sublimetext.com/docs/2/osx_command_line.html) but when I ran 

`ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" ~/bin/subl`

I just got a 'no such file or dir exists error'. I didn't try too hard though, so will make another attempt.

**Comment by jldimond** [comment]
# Most fun

Being able to visualize and think about directory structure more the way your computer sees it as opposed to the Finder windows. 

# Least fun

The above can also be an issue if you do not have a good grasp of your directory structure. I am still more efficient in the Finder (e.g. dragging and dropping vs. using mv or cp).

**Comment by Ellior2** [comment]
Most fun: Realizing the power that exists in the command-line. It's really exciting when I don't get an error message (although I realize this could potentially be a terrifying thing at the same time)! I look forward to becoming more comfortable with it as I start to actually process data.

Least fun: Trying to visualize the way my computer works in a different way. For example, I can see the importance in using pipes when working with huge datasets but I imagine as a new user it will be challenging to not see those intermediate outputs.

**Comment by nclowell** [comment]
**Most Fun**: Executing clear and powerful commands and learning to speak computer.

**Least Fun**: Feeling like I might actually delete things I need and not know it, silent errors, etc.

**Comment by mmiddleton** [comment]
Most fun: I usually use a mac desktop computer but I'm using a windows laptop for the class, so the thing I enjoyed most was learning how to open things from the command line on a windows computer. More often than not I can't figure out how to open a file on the windows operating system because even though I remember where I put it, I can't figure out how to get there from the desktop. 

Least fun: I felt like the tutorial was really mac based so it was a little difficult to get through on the windows operating system the first time around since I have so little experience working from the command line. Also, the fact that you could potentially delete everything on your computer based on a single space is beyond terrifying.
