### ISSUE TITLE
extrating information nested in a column

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#100]
I want to extract Uniprot Accession codes from the following file: 

[blastx matches; codes in second column](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/blastx-11-14-best-matches)

I was planning on using the Galaxy, but the file modifications are taking more than a day. Any suggestions on a faster way to do this?

**Comment by sr320** [comment]
Practically, what do you literally need to do to the file?

**Comment by yaaminiv** [comment]
I want to remove the extraneous information from the second column and have only the accession codes (i.e. sp|P07104|FANA_ECOLX --> P07104). I was using the "Trim" tool in Galaxy, but it has yet to complete the job.

**Comment by yaaminiv** [comment]
I ended up using the code `tr '|' '\t' < file` to convert all pipes to tabs in my file, giving me a separate column with accession codes.
