### ISSUE TITLE
DAVID error when uploading background genes

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#102]
When I uploaded my accession codes, I got the following error from DAVID

![05-daviderror](https://cloud.githubusercontent.com/assets/22335838/20983784/995a264c-bc72-11e6-9fa2-c0a8c83bb237.png)

I wanted to ensure that I did in fact isolate the accession codes before I continued with Option 1 (see above). Here is my [file that lists contigs and accession codes](https://raw.githubusercontent.com/yaaminiv/yaaminiv-fish546-2016/master/analyses/oly_oa_gonad_GO_enrichment/uniprot_accession_codes.txt).

Full notebook [here](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-11-30-oly-gonad-OA-part6-enrichment-analysis.ipynb)

Did I make a mistake, or can I continue?

**Comment by sr320** [comment]
You can continue
