### ISSUE TITLE
interpreting DAVID functional annotation tool

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#103]
I watched the [video about DAVID](https://www.youtube.com/watch?v=D2XjF2xqbF4&feature=youtu.be) and ran my analyses ([notebook here](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-11-30-oly-gonad-OA-part6-enrichment-analysis.ipynb)).

I downloaded a whole slew of files:
- GO charts on [biological processes](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/oly_oa_gonad_GO_enrichment/GO_BP_DIRECT.txt), [cellular component](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/oly_oa_gonad_GO_enrichment/GO_CC_DIRECT.txt) and [molecular function](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/oly_oa_gonad_GO_enrichment/GO_MF_DIRECT.txt)
- [cluster analysis](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/oly_oa_gonad_GO_enrichment/GO_DAVID_clustering.txt)
- [annotation table](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/oly_oa_gonad_GO_enrichment/GO_DAVID_annotation_table.txt)
- [interpro table](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/analyses/oly_oa_gonad_GO_enrichment/GO_DAVID_INTERPRO.txt)

I have all of this information but no idea how to understand it. I also don't know if there's something else I should look at that I don't have here. Any ideas?

**Comment by sr320** [comment]
Great item to tackle tomorrow in class!
