### ISSUE TITLE
new problems with github

### ISSUE THREAD

**Issue by mfisher5** [sr320/course-fish546-2016#106]
I am trying to push some changes to my repo from my desktop to github, and keep getting the error `"Large files detected... this exceeds GitHub's file size limit of 100MB"`. Last week I accidentally tried to push a large `.fasta` file from my desktop to github, but after github failed to push the files I deleted the `.fasta` file from that folder. Since I was still getting the same error as above even after deleting the file, I created a `.gitignore` file, but this still hasn't resolved the error. I can't push any new changes online until I figure out how to get around this file - please help!

**Comment by sr320** [comment]
On the desktop app you should be undo a commit? Once you undo a commit you
can add any files to .gitignore.

**Comment by laurahspencer** [comment]
I had the same issue; I had to reset a few commits, which uncommitted the file changes but did not modify any of the actual files. Below is the script I used, but I highly recommend looking up the `git reset --soft HEAD~<# commits to reset>` command online to see if this is what you want, as I am no expert:

`git log --oneline` _this shows you the recent commits, most recent at the top_
`git reset --soft HEAD~<number of commits to reset>` _this resets the commits; I've been told to be very careful wit this command; if there were changes to the file elsewhere (by someone else, or you via a different computer) it could muck things up.  
`git reset .` 
`git status`

**Comment by MeganEDuffy** [comment]
I have had this problem, too!  My solution was to delete that file's cached history, which I think was causing me to be unable to use ```git push```. I did this using ```filter-branch```:
```
git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch big-file.file' -f HEAD
```
