### ISSUE TITLE
Finding data for class projects

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#15]
Where is a good place to start looking for data for class projects? Personally, I'm looking for shellfish transcriptome data (maybe from an OA experiment?)

**Comment by jldimond** [comment]
If it were me, I would start looking for articles on say Google Scholar that involved transcriptome analyses of shellfish. The article will almost always provide you with a link to their data. If not, you at least will find out that such data exists and maybe find it on NCBI by doing a search for a certain species.

**Comment by sr320** [comment]
Here is a [data set from _Ostrea lurida_](https://fusiontables.googleusercontent.com/embedviz?viz=CARD&q=select+*+from+13IxnqIZ_2Xpz_HE-3YcnU_egASYz9ZlA0PYIDGLN+where+col2+%3D+%27O_lurida%27+and+col6+%3D+%27PE72%27&tmplt=3&cpr=2) where male and female gonads were sequenced - in OA treatment and control

**Comment by sr320** [comment]
Related if anyone else is looking.. here is a bunch of NGS data that can be filtered by taxa etc.
https://fusiontables.google.com/DataSource?docid=13IxnqIZ_2Xpz_HE-3YcnU_egASYz9ZlA0PYIDGLN&pli=1#rows:id=1
