### ISSUE TITLE
Project Status update

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#17]
As you recall each week project progress counts as three points! ⭐️  ⭐️  ⭐️  [details](https://github.com/sr320/course-fish546-2016/wiki#grading)

For this week please simply provide 

1 ) the url for your course repo 
2) either a url for your data, a url for a readme.md describing the data, or a request for suggested data that you might like to examine 

Remember to use `Issues` for any questions you have our just to share information that you think others might appreciate 
thanks

**Comment by hputnam** [comment]
https://github.com/hputnam/Oly_Oyster_DNA_Methylation

https://github.com/hputnam/Oly_Oyster_DNA_Methylation/blob/master/Oly_MBD_Metadata.md

**Comment by yaaminiv** [comment]
[Course repo](https://github.com/yaaminiv/yaaminiv-fish546-2016)
[Data](https://fusiontables.googleusercontent.com/embedviz?viz=CARD&q=select+*+from+13IxnqIZ_2Xpz_HE-3YcnU_egASYz9ZlA0PYIDGLN+where+col2+%3D+%27O_lurida%27+and+col6+%3D+%27PE72%27&tmplt=3&cpr=2)

**Comment by mmiddleton** [comment]
Course repo: https://github.com/mmiddleton/mmiddleton-fish546

Readme.md describing data: https://github.com/mmiddleton/mmiddleton-fish546/blob/master/README.md

**Comment by aspanjer** [comment]
repo: https://github.com/aspanjer/RNAseq_Coho

readme: https://github.com/aspanjer/RNAseq_Coho/blob/master/data/README.md

**Comment by jldimond** [comment]
[repo](https://github.com/jldimond/jldimond-fish546-2016)

[data](https://github.com/jldimond/jldimond-fish546-2016/tree/master/data)

**Comment by mfisher5** [comment]
_course repo:_ https://github.com/mfisher5/mf-fish546-2016
_READme on data:_ https://github.com/mfisher5/mf-fish546-2016/tree/master/data

**Comment by nclowell** [comment]
**course repo**:
https://github.com/nclowell/student-fish546-2016

**data**:
https://github.com/nclowell/student-fish546-2016/blob/master/Cod-Time-Series-Project/README.md

**Comment by laurahspencer** [comment]
**Project repo:** 
https://github.com/laurahspencer/FISH-546-Bioinformatics

**Data:**
http://owl.fish.washington.edu/P_generosa_genome_assemblies_BGI/20160512/
(thanks!)

**Comment by Ellior2** [comment]
[Course Repo](https://github.com/Ellior2/Fish-546-Bioinformatics)

[Readme](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/README.md)

**Comment by MeganEDuffy** [comment]
[course repo](https://github.com/MeganEDuffy/FISH-546)

[some data](https://github.com/MeganEDuffy/FISH-546/tree/master/data)
