### ISSUE TITLE
The week ahead

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#18]
This week we will taking much of what we have learned from the readings
and tutorials. 

On Tuesday we will walk through using BLAST from the command-line.
If you can go ahead install BLAST on your machine
ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/

Be sure to read this weeks material

```
Retrieving Bioinformatics Data 109-124, Unix Data tools 125-168
```

Minimally tackle the 109-124 by Tuesday. 

Also, be thinking about what the first step in your project might be.

Thursday we will be exploring our BLAST results with `Unix Data tools 125-168`
and other tools we have learned. 

Logistics-wise, use should create a sub-directory in your repo to carry out these analyses in 
Jupyter. 

I will not be physically in class on Thursday, but will start a Google Hangout to
join at 10:15.

**Comment by Ellior2** [comment]
I am having some issues installing BLAST. Not sure what links to try- I have tried all of these:
- ncbi-blast-2.5.0+-win64.exe  (This one was the most promising and I went through the installation process a 3 times but it never ended up my Windows PC)
- ncbi-blast-2.5.0+-5.src.rpm
- ncbi-blast-2.5.0+-5.x86_64.rpm
- ncbi-blast-2.5.0+-x64-win64.tar.gz

Am I missing something?

**Comment by sr320** [comment]
How do you know it is not on your pc?
Was there an error message during the installation process?

See also https://www.ncbi.nlm.nih.gov/books/NBK52637/?report=classic

**Comment by Ellior2** [comment]
Alright maybe I do have it. I was too quick to assume that this BLAST software package would have been listed in my program files or that I would be able to search for it... I can only tell that I have it by typing in some commands in my shell.
