### ISSUE TITLE
Make a pull request

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#19]
Select a course-repo of one of your classmates

![repos](http://eagle.fish.washington.edu/cnidarian/skitch/Home_·_sr320_course-fish546-2016_Wiki_1DABE2F4.png)

Make a simple edit to a markdown file - creating a pull request that they can then review and decide whether to accept.

**Once you have done this provide the url of the pull request**
ie https://github.com/hputnam/Oly_Oyster_DNA_Methylation/pull/1

(note that the url I provided is  `https://github.com/hputnam/Oly_Oyster_DNA_Methylation/pull/1` but GitHub automagically renders it with more meaning).

[Here is an example](http://d.pr/i/oZnS)

**Comment by yaaminiv** [comment]
**Pull request on Laura's repository**: https://github.com/laurahspencer/FISH-546-Bioinformatics/pull/2

**Comment by Ellior2** [comment]
Pull request on Natalie's repository: https://github.com/nclowell/student-fish546-2016/pull/1

**Comment by jldimond** [comment]
https://github.com/aspanjer/RNAseq_Coho/pull/1

**Comment by mfisher5** [comment]
https://github.com/nclowell/student-fish546-2016/pull/2

**Comment by aspanjer** [comment]
https://github.com/MeganEDuffy/FISH-546/pull/2

**Comment by MeganEDuffy** [comment]
https://github.com/mfisher5/mf-fish546-2016/pull/3

**Comment by mmiddleton** [comment]
Pull request: https://github.com/Ellior2/Fish-546-Bioinformatics/pull/3

**Comment by laurahspencer** [comment]
https://github.com/Ellior2/Fish-546-Bioinformatics/pull/4
