### ISSUE TITLE
Briefly describe your background in this area

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#2]

**Comment by yaaminiv** [comment]
I have limited experience using Blast and Phamerator when annotating bacteriophage genomes. I have never used command line before, nor have I worked with very large genomics data sets, so this will all be new for me.

**Comment by laurahspencer** [comment]
My background in this topic is slim to none, so I am very excited to delve into this course! I think that taking R concurrently will help me with some of the command line concepts/language, but overall everything is new.

**Comment by Ellior2** [comment]
I have little to no experience in any of these programs. I used R for a Biostats class in undergrad (7 yrs ago :blush:) and that is about the extent of my scripting language knowledge. Otherwise everything is new!

**Comment by mfisher5** [comment]
I took an intro to python course in the genomics department, so have used the command line to execute some simple code, and had a brief introduction to large genomic data sets. I'm also taking the into R class this quarter, and have used R in the past for a biostats class and for research (which mostly involved copying other people's code). I'm also learning stacks to process my RADseq data, but haven't gotten very far through the pipeline!

**Comment by aspanjer** [comment]
Through the analysis of a RNAseq data set I've become familiar with the challenges of moving around large data files and the limits of different hardware setups for processing large data sets. I've used a number of scripts through the galaxy web interface, but I'm much less comfortable running these same scripts on my local machine at the command line. I feel comfortable with blast+ at the basic level of building and querying local databases for annotations. In terms of scripting languages, I'm generally more familiar with R (vs. python or pearl) and to a limited extent have used the bioconductor package within R.

**Comment by MeganEDuffy** [comment]
I have run a few open source tools for de novo peptide sequencing and database generation from the command line, and in the process have started using GitHub and Anaconda to document my work and manage environments. I have taught myself some Python (but no R), but am still not very comfortable with it. I have used the Trans Proteomic Pipeline built at ISB and took a course on using those tools there this past winter.

**Comment by nclowell** [comment]
I took the SAFS R class and the genomics Bioinformatics in Python class. I'm pretty comfortable doing basic things in R and python, but haven't applied these skills to giant data sets yet.

**Comment by mmiddleton** [comment]
I have little to no experience in this area so most of this course will be new information for me. I work with a few people who do work in bioinformatics and have talked with them about their work and the trials that come with it. As far as using the programs go I haven't used any in the list, but I have used R a small amount for very basic statistics.
