### ISSUE TITLE
Create an Issue

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#20]
Identify at least one issue you would like assistance on relating to one of the following topics
- Unix
- Bash 
- GitHub

It could be how to do a simple task, improve your current workflow, reduce redundant actions, or a simple curiousity etc.
**Once you [create an issue](https://github.com/sr320/course-fish546-2016/issues/new)**

add the url below
ie https://github.com/sr320/course-fish546-2016/issues/16

(GitHub translates `https://github.com/sr320/course-fish546-2016/issues/16` to hyperlink above.)

**Comment by mfisher5** [comment]
[Issue #21](https://github.com/sr320/course-fish546-2016/issues/21)

**Comment by yaaminiv** [comment]
#23

**Comment by Ellior2** [comment]
[#24](https://github.com/sr320/course-fish546-2016/issues/24)

**Comment by nclowell** [comment]
https://github.com/sr320/course-fish546-2016/issues/25

**Comment by jldimond** [comment]
[#28](https://github.com/sr320/course-fish546-2016/issues/28)

**Comment by MeganEDuffy** [comment]
[#29](https://github.com/sr320/course-fish546-2016/issues/29)

**Comment by aspanjer** [comment]
https://github.com/sr320/course-fish546-2016/issues/33

**Comment by mmiddleton** [comment]
https://github.com/sr320/course-fish546-2016/issues/35

**Comment by laurahspencer** [comment]
https://github.com/laurahspencer/FISH-546-Bioinformatics/issues/3

**Comment by laurahspencer** [comment]
https://github.com/sr320/course-fish546-2016/issues/38
