### ISSUE TITLE
Showing subdirectories in a repository

### ISSUE THREAD

**Issue by mfisher5** [sr320/course-fish546-2016#21]
Is there a way to make subdirectories within a repository show up on the desktop GUI or online without a file in them? For example, in our class repo we have "data," "analysis," "scripts," and "notebooks," but only "data" is actually visible on github because it has a readme file in it. Can I make the others visible as well, without adding a file?

**Comment by MeganEDuffy** [comment]
This has always bothered me about GitHub, but I'm sure this feature exists for a reason (?)
You can create directories automatically when adding a file within them in GitHub, in the past I've created directories by adding a dummy file (.tmp or .gitignore or something) just so I can have the directory visible.  I don't know of any way to just make a directory.
