### ISSUE TITLE
Images from computer vs. repo

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#23]
I know you can insert a photo from your github repo in a markdown post, but is there any way to insert an image from your machine without it being hosted on github? I'm assuming there isn't a way to do this, but I'm just curious!

**Comment by sr320** [comment]
Correct it has to be hosted somewhere on the internet (and publicly accessible).
Other options are
Dropbox (maybe)
on a NAS (ie owl)
Evernote (maybe)
Google Drive
Droplr
really any website where the image is visible and you can grab a url
