### ISSUE TITLE
Jekyll page build failed

### ISSUE THREAD

**Issue by Ellior2** [sr320/course-fish546-2016#24]
When I modify the _config.yml file which should force GitHub pages to rebuild by site with Jekyll I get an email that says:

The page build failed with the following error:

The value 'nil' was passed to a date-related filter that expects valid dates in `sitemap.xml` or one of its layouts. For more information, see https://help.github.com/articles/page-build-failed-date-is-not-a-valid-datetime/.

It recommends that I build my Jekyll site locally so that I can debug and fix these issues before pushing them to GitHub.  Trying to do that opened up a whole new can of worms. Just wondering if it anyone else is getting these error messages.

**Comment by sr320** [comment]
Just so we do not confuse / scare anyone. 
There is no requirement to build Jekyll pages for course, yet...

I do not see Jekyll docs in your course repo... but do see them in 
https://github.com/Ellior2/Ellior2.github.io

When you go to settings, take a screen shot of GitHub Pages section and this will help troubleshoot.

**Comment by Ellior2** [comment]
![capture3](https://cloud.githubusercontent.com/assets/20071030/19254672/f50f7446-8f0a-11e6-88c2-9545c66cb0a4.PNG)

**Comment by sr320** [comment]
Try deleting
`http:https://github.com/Ellior2`
in line 43..

I presume if you go back to the config file before you edited, the page
rendered ok?

**Comment by Ellior2** [comment]
Yay! I am up and running. I tried deleting that and some other things which didn't work so I just deleted the whole thing and tried again taking extra care to not "break" the code in the _config.yml file. Thanks Steven!
