### ISSUE TITLE
when to use Unix or python/r script

### ISSUE THREAD

**Issue by nclowell** [sr320/course-fish546-2016#25]
The reading material on Unix tools reminds me of similar functions in R and python. The reading briefly mentioned that there are times for a tailored script in these languages, and other times to operate in bash. But it's not totally clear to me when to do which. 

Is it just that I'm more familiar with R/python that I would rather do the same tasks in those languages? Is it really more efficient/better to do data manipulation in bash?

**Comment by sr320** [comment]
Good question - what ever works for you is best. The main point is that you document it in a manner that is reproducible.
