### ISSUE TITLE
BLAST INSTALLATION - problems downloading data

### ISSUE THREAD

**Issue by mmiddleton** [sr320/course-fish546-2016#27]
Using Windows 8

When trying to download data from owl.fish.washington.edu I got this error message:
Access is denied
This is what I typed that caused me to get that message:

```
!curl http://owl.fish.washington.edu/fish546/course-data/Oly-transcriptome-2k.fa \
> /Users/Mollie.Middleton/Documents/GitHub/data
```

Also, when working with BLAST typing: 

```
!/Program Files/NCBI/blast-2.5.0+/bin/blastp
!blastp
```

AND

```
!blastp -help

```

all resulted in nothing happening after hitting "shift-enter"
I can navigate there by clicking through the files on my computer so I know that I downloaded it and there is something there, but nothing happens in jupyter,  not even an error message

**Comment by sr320** [comment]
For data downloads- I suggest using mouse clicks etc. 
My take is that you will not be using that machine for regular bioinformatics analysis.
If I am wrong I have several options to set up the environment, including the use of Docker. 

For Blast- It is worth getting that installed and working properly on that machine.
Can you explain how you installed Blast? 
That will help in troubleshooting

**Comment by mmiddleton** [comment]
For data downloads - Mouse clicks are totally fine with me, if I have problems in the future on my mac I'm sure that I can find out what is going on from someone around NOAA.

For Blast - Unfortunately I don't have that computer with me right now, but as I recall I copied the link from this weeks announcement, clicked on the link at the top which opened an installer window asking which directory to put it in, I clicked ok, the download completed and I checked to make sure that there was an NCBI folder with stuff in it in that directory, which there was.

Would it be possible to post how to go through this on a mac so that I can try it out on that computer instead?

**Comment by sr320** [comment]
I created a two part series for installing BLAST on a Mac.

[Part 1](https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=e753f49a-e371-482a-8c56-297f115c8a56)

[Part 2](https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=61943995-45c6-46a2-9976-aadc6f42e43b)

**Comment by sr320** [comment]
For Blast installation on Windows -
I would suggest following this guide
https://www.ncbi.nlm.nih.gov/books/NBK52637/?report=classic

The other thing you might try first is typing `blastp` in the bash terminal. (I doubt anything will happen)
