### ISSUE TITLE
The exclamation point!

### ISSUE THREAD

**Issue by jldimond** [sr320/course-fish546-2016#28]
What function does the ! serve before a command in jupyter notebook? Some Bash commands, like `cd` for example, do not like a ! before them, while others like `ls` or `pwd` don't seem to care:

<img width="1095" alt="screen shot 2016-10-11 at 5 45 35 pm" src="https://cloud.githubusercontent.com/assets/9869457/19293611/b3fde0a2-8fda-11e6-9511-acce566f6c58.png">

**Comment by sr320** [comment]
> When you run a bash command, it must be prefixed with an exclamation point ("!"). The exclamation point tells Jupyter that the line should be run through bash as though it were run on the terminal. So for instance, let's list out all of the files in the current working directory using a long listing.

This really does not answer your question as it is not clear why '!cd' does not do what you want..

Just for everyone else- and to clarify what I indicated yesterday - when we are not running bash commands you do not need ❗️ 

This is a decent post on the variety or things you can do..
https://wp.sanger.ac.uk/barrettgroup/2016/03/10/how-jupyter-notebooks-will-improve-your-computational-life/

**Comment by jldimond** [comment]
Thanks - here is one explanation I found (a little over my head):

http://stackoverflow.com/questions/36512527/cd-vs-cd-vs-cd-in-ipython?rq=1
