### ISSUE TITLE
Editing PATH variable in .bash_profile for blast 

### ISSUE THREAD

**Issue by MeganEDuffy** [sr320/course-fish546-2016#29]
Ok, so this is a Unix thing I've been trying to figure out today, and it relates to installing and using blast as we did today. (As I started writing this issue, I started working on the problem and kind of solved it for now, but I thought I'd post it anyway as it might be useful to other people.)

What I want to do is have bash run from my shell without me having to preface it with its complete path, as many of us had to do today in class. What I want to do is edit my profile file, which is a UNIX start-up file that executes system files to set up the user account before returning the prompt to the user in the shell. I know that this requires setting up a PATH, or an environment variable, that specifies the set of directories where executable programs (like blastp, makeblastdb) are located

I had had unsuccessfully tried to do this before, and edited my .profile file. From doing some [reading](http://www.theunixschool.com/2011/07/what-is-profile-file.html) online, it seems like Bash's profile file is called .bash_profile. So I edited that instead:

I opened up my .bash_profile in nano (in command line `nano ~/.bash_profile`)

```
# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

# added by Anaconda3 4.1.1 installer
export PATH="/Users/meganduffy/anaconda/bin:$PATH"
```

and to this file I added the lines:

```
# added on 10.11.16 to for blast 2.5.0+
export PATH="Users/meganduffy/Applications/ncbi-blast-2.5.0+/bin:$PATH"
```

Then I wrote to the file (ctl-o), exited nano (ctl-x), ended that terminal window and started another. Now when I input `blastp` in the command line, I don't get the error that such a command doesn't exist, I just get told that I have a BLAST query/options error.

**Comment by sr320** [comment]
Nice!

Here are some instructions that are similar but uses your systems default text editor.

https://github.com/sr320/LabDocs/blob/9073dc7caf2dcf40e7739fc7ce9d922b28468dc3/code/bash.md#add-program-to-path

⬆️ a markdown file where our lab compiles useful bash commands.

**Comment by MeganEDuffy** [comment]
Cool, thanks! This is a great resource for Bash commands.
