### ISSUE TITLE
What do you hope to get out of the class?

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#3]

**Comment by yaaminiv** [comment]
I hope to learn techniques I can apply towards my own research projects, ranging from data management to analysis. I also want to become more familiar with GitHub to promote open and reproducible science. Bioinformatics seems like the "next big thing" in our field, and I would like to start thinking in this type of mindset when framing research questions.

**Comment by laurahspencer** [comment]
Broadly, I hope to gain further insight into how genomic and proteomic research tools are used to address fisheries science questions so I can begin formulating a research idea/plan. My goal is to first learn the language of bioinformatics in order to understand colleague's work and begin to play around with the tools. Then, I hope to be able to consider which tools/software and methods will be effective at answering potential thesis questions, then to apply tools on my own (future) data analysis.  Finally, I hope to feel comfortable communicating effectively on this topic (discussing methods of analysis, issues encountered, presenting, etc.).

**Comment by Ellior2** [comment]
I am excited to begin learning some of the tools used in the field of proteomics and genomics to answer some of our research questions. I want to be able to understand the language and become more familiar with programs such as R, python, and Github. Creating an online lab notebook has been a goal of mine over the years and I look forward to creating a space where we can collaborate and share knowledge. Perhaps by understanding how to manage and analyze data sets, I would gain insight on how to better design experiments in the future.

**Comment by aspanjer** [comment]
I am hoping to learn more "best practice" techniques when it comes to both bioinformatics and reproducible science. Having done limited bioinformatics work, I've found it easy to get ahead of myself with the multitude of data analysis pipelines and soon find myself lost both organizationally and in terms of answering the question I'm after. Additionally I'm excited to see what other questions are being answered using these tools, learn more about genetics beyond gene expression, and most importantly use the class project as a catalyst for turning my RNAseq dataset into a publication.

**Comment by MeganEDuffy** [comment]
#### some of my goals for this course:
1. Develop the skills to make pipelines that go from raw proteomic data to managed outputs in an efficient, script-based manner while getting a fuller picture of the open source tools available.
2. Be able to better assess the quality of my raw and processed data.
3. Have a better understanding of the genomic data + processing that goes into generating the assembled metagenomes I currently use for metaproteomic database searches.
4. Develop well-documented project management practices with GitHub and learn how and where to access shared datasets that could inform my research.

**Comment by mfisher5** [comment]
I would like to become more familiar with the various programs that are used to manage and process large amounts of genomic data; I'll have to analyze SNP data for my current research, but I'd also like to be exposed to other types of data and analyses. By doing so, I'm hoping to get a better understanding of all of the questions that can be answered with genomic / proteomic data, and be prepared for future research experience. In a more technical sense, I'd like to become more familiar with GitHub as a resource for accessing shared data and code, and learn specific data analyses that I can use to explore my own RADseq data.

**Comment by nclowell** [comment]
Goals for the course:

(1) I want to learn how to use some of the programs that I will need to process my data sets and become familiar with bioinformatics pipelines.

(2) I want to write more efficient and more useful (to other people) code.

(3) I want to get in the hang of using git hub for my research.

**Comment by mmiddleton** [comment]
My main goal for the course is to be able to better understand how to deal with large genomic datasets. It seems that our lab's research is headed in a direction where we will be dealing with a lot of this type of data in the coming years so I would like to be able to keep up. I hope that by taking this course I'll be able to make a larger contribution to discussions about the research and analysis of the data.
