### ISSUE TITLE
Short Git Course

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#30]
If you like the idea of Git (What GitHub is using) and want to learn how to interact with Git at the command line. The eScience Institute is running a short course next week.

https://docs.google.com/a/uw.edu/forms/d/e/1FAIpQLSd2w4uJPTEx9ZxsOtgPd0-nK21vuB3hc0eBGx5jBQSokwOmWA/viewform

**Comment by yaaminiv** [comment]
I tried opening the form but I got a message saying that they were no longer accepting responses. Has registration closed?
