### ISSUE TITLE
Project Data - Paste Jupyter url

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#31]
For this week's "Project Progress" I would like everyone to provide a url for a Jupyter notebook where we can see some aspect of your data (ie `head, tail, grep, wc, less, awk` etc.  In the same notebook describe where it came from and any other general characteristics. 
Please paste the url to your Jupyter page below.

**Comment by aspanjer** [comment]
https://github.com/aspanjer/RNAseq_Coho/blob/master/RNAseq%20Analysis.ipynb

**Comment by jldimond** [comment]
https://github.com/jldimond/jldimond-fish546-2016/blob/master/notebooks/data1_assembly.ipynb

**Comment by mmiddleton** [comment]
https://github.com/mmiddleton/mmiddleton-fish546/blob/master/O.%20mykiss%20sperm%20RRBS.ipynb

**Comment by Ellior2** [comment]
[Sneak Peak](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/000-sneak-peak.ipynb)

**Comment by yaaminiv** [comment]
https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/2016-10-13-oly-gonad-OA.md

**Comment by MeganEDuffy** [comment]
[exploring test datafiles](http://localhost:8888/notebooks/notebooks/data/01-etnp_mgf.ipynb)

**Comment by laurahspencer** [comment]
http://localhost:8888/notebooks/Documents/SAFS/FISH_546_Bioinformatics/GitRepo_FISH-546-Bioinformatics/Geo-Ann-Project/Jupyter/Geoduck%20Annotation%20Project.ipynb

on second thought...
I wasn't able to sync the my GitHub desktop repository for this course to the cloud; instead please check out this [copy of my Jupyter notebook](https://github.com/laurahspencer/FISH-546-Bioinformatics/blob/master/2016-10-14-Geo-Ann-Project.md).

UPDATE: I rebuilt my course repository locally then pushed it to GitHub; that seemed to work: here's the Jupyter [notebook](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/Jupyter/Geoduck%20Annotation%20Project.ipynb)

**Comment by nclowell** [comment]
https://github.com/nclowell/Cod-Time-Series-Project/blob/master/Cod%20Time%20Series%20Project.ipynb

I still don't have data! A collaborator was supposed to bring a hard drive with the data on Tuesday, but forgot, and then I was off to PCSGA. I will get a hold of it on Monday but I realize that I've made no progress on my project because of it. Yikes!

**Comment by mfisher5** [comment]
[Jupyter notebook]](https://github.com/mfisher5/mf-fish546-2016/blob/master/data/Pcod%20Raw%20Data%20-%20Overview.ipynb)

**Comment by mfisher5** [comment]
[Jupyter notebook](https://github.com/mfisher5/mf-fish546-2016/blob/master/data/Pcod%20Raw%20Data%20-%20Overview.ipynb)
