### ISSUE TITLE
Control of email notifications

### ISSUE THREAD

**Issue by aspanjer** [sr320/course-fish546-2016#33]
Is there a way to control the number of emails I'm getting from git. Since "watching" the issues from this site I get an email every time someone posts an answer to a quiz question or response to an issue. I would like to receive notification when quiz questions and class issues are posted, but perhaps not every response to them. Suggestions?

**Comment by sr320** [comment]
I filter in my email app (Gmail) ie bundle, skip, etc

There are also some setting at https://github.com/settings/notifications

**Comment by sr320** [comment]
You also have the mute option @ the bottom of your email
