### ISSUE TITLE
GitHub Desktop

### ISSUE THREAD

**Issue by mmiddleton** [sr320/course-fish546-2016#35]
I am curious if there are large merits to using GitHub Desktop over just doing the things that you want (creating files, editing, etc.) on the website. I haven't gone too in depth as to what GitHub Desktop can do for you, but I was just wondering if there was really much of a difference between the two options beyond needing an internet connection to work through the website. So far, I have found it easier to work through the website myself.

**Comment by sr320** [comment]
You are correct, but you cannot create certain files on the web (ie Jupyter Notebooks, your analyses outputs etc.) GitHub Desktop is just a app that "syncs" files from your local copy to the cloud
