### ISSUE TITLE
creating a blast database

### ISSUE THREAD

**Issue by mfisher5** [sr320/course-fish546-2016#36]
I'm working off of the notes on how to create a blast database, and am having trouble getting the code to execute - Jupyter says that it is running the code, but nothing is coming up on the screen and it seems to be frozen. I'm in my blast tutorial directory under the class repo, and am trying to run the following: 

`!makeblastdb -in ../../data/uniprot_sprot.fasta -dbtype prot -out uniprot_sprot_r2013_12`

Since I'm on windows, when we were working on Tuesday I didn't have to specify a path for blast. Should I be in the blast directory instead, and using the full path for the data file?

**Comment by sr320** [comment]
One way to go is to navigate to the directory where your fasta file is located. 
confirm by typing `ls` and you should see:
`uniprot_sprot.fasta`

then (in theory) all you would have to type is.

`!makeblastdb -in uniprot_sprot.fasta -dbtype prot -out uniprot_sprot_r2013_12`

**Comment by sr320** [comment]
The other thing you could try, to try troubleshooting.

Is do the same thing in BASH.  This would identify if Jupyter is in some way an issue.

**Comment by mfisher5** [comment]
Thanks! That seems to have worked.

**Comment by sr320** [comment]
🎉 
To clarify - navigating to the directory via Jupyter worked, or you had to go to the BASH terminal?

**Comment by mfisher5** [comment]
I navigated into the directory where my file was via Jupyter, and then ran the code to output the blast database in that directory as well.
It also just seems to be taking my PC a very long time to execute the blast commands, so that may have had something to do with it as well.
