### ISSUE TITLE
PC not powerful enough to execute Blast?

### ISSUE THREAD

**Issue by Ellior2** [sr320/course-fish546-2016#37]
I think my PC is having a really hard time executing the blast. I've tried several times over the past few days and I think I have the right commands, but it just will say busy for a minute or so and then not do anything. I even tried leaving it overnight... still nothing by morning. Here is a picture of my latest attempt.
![capture](https://cloud.githubusercontent.com/assets/20071030/19367018/46686ace-914e-11e6-9e91-1bd4fa6f3cf9.PNG)

**Comment by sr320** [comment]
Power should not be an issue. Can you make the query smaller file and redirect the output to a file. 

A simple way to make a smaller query..
(you would have to fill in absolute path............)
`!head ...................2k.fa > ......................2kshort.fa`

then when doing blast.

after 
`-outfmt 6`

`> ....................blastoutput.txt`

**Comment by Ellior2** [comment]
Great idea. Thank you Steven! Worked like a charm.
