### ISSUE TITLE
Do you use GitHub on your desktop, browser, or both? 

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2016#38]
After installing the GitHub app on my computer I find that I don't actually use it, and instead work exclusively in the browser-based program. I'm curious if ya'll have found that the desktop app is important/useful, how you move between the two platforms (how frequently do you sync them up)?

Also- on my GitHub ["page" (aka lab notebook blog)](https://laurahspencer.github.io/LabNotebook/) the [admin button links](https://github.com/sr320/sr320.github.io/tree/master/_posts) to @sr320 GitHub. Does anyone know where I fix that? Thanks!

**Comment by sr320** [comment]
See also https://github.com/sr320/course-fish546-2016/issues/35#issuecomment-253590415

I will make pull request to fix the link issue.
