### ISSUE TITLE
Can you stream data from owl in Jupyter/BLAST?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2016#39]
Is it possible to use `head` to check out a file prior to downloading it from the web, aka streaming it from the web using a site address? 

Similarly, I'd like to learn _**more**_ about running a program on my laptop while streaming from a file located on another location.

**Comment by sr320** [comment]
Couple of things
1) you can mount `owl` so that it looks like a usb drive plugged into your laptop. No need to download (see https://github.com/sr320/course-fish546-2016/issues/22)

2) Yes, you could `curl | head`.

**Comment by laurahspencer** [comment]
Great-Thanks!  I was able to successfully use the `curl | head` commands. I subsequently downloaded the genome file to my computer to play with it in Jupyter. I'll plan on mounting owl on my computer at a later date when I have more significant computing needs.
