### ISSUE TITLE
Getting Set-Up

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#4]
Here are _some_ of the tasks for this week, 
- [ ] GitHub Account, Install Local GitHub client
- [ ] Bash Installed
- [ ] Become familiar with Markdown
- [ ] Install good Text Editor
- [ ] Install good Markdown Editor

Once completed, respond with
1. Your OS
2. Your Text Editor
3. Your Markdown Editor

**Comment by mfisher5** [comment]
**OS:** Windows 10
**Text Editor:** Notepad++
**Markdown Editor:** Haroopad

**Comment by yaaminiv** [comment]
1. **OS**: MacOS Yosemite 10
2. **Text Editor**: TextWrangler
3. **Markdown Editor**: Mou

**Comment by laurahspencer** [comment]
1. OS: Mac OS X El Capitan
2. Text Editor: TextWrangler
3. Markdown Editor: Mou

**Comment by MeganEDuffy** [comment]
1. **OS:** MacOS Sierra (10.12)
2. **Text Editor:** Sublime Text 2
3. **Markdown Editor:** Byword

**Comment by Ellior2** [comment]
1. **OS**: Windows 10
2. **Text Editor**: Notepad ++
3. **Markdown Editor**: Haroopad

**Comment by aspanjer** [comment]
1. **OS:** MacOS Sierra (10.12)
2. **Text Editor:** TextWrangler
3. **Markdown Editor:** MacDown

**Comment by nclowell** [comment]
1. **OS:** MacOS X Yosemite 10.10.2
2. **Text Editor**: Text Wrangler
3. **Markdown Editor**: Mou

**Comment by mmiddleton** [comment]
OS: Windows 8
Text Editor: Notepad ++
Markdown Editor: Haroopad
