### ISSUE TITLE
jupyter failing to run python commands

### ISSUE THREAD

**Issue by mfisher5** [sr320/course-fish546-2016#40]
I just installed Jupyter on a desktop computer and am trying to run several commands (gunzip, zcat), but they are returning as an unrecognized internal or external command. I can change and add new directories from Jupyter, and I can run all of the code from the command line on my computer, but it will not run through Jupyter. I reinstalled Anaconda and the correct version of python, but its still not working... any suggestions?

**Comment by sr320** [comment]
Few questions
OS?
What exactly are you typing, what exactly is the error.  (screenshots ok)
Sounds like `!mkdir` and `cd` work in Jupyter?
Show what commands you are running in bash terminal.
Type `!which bash` in Jupyter, and `which bash` in the command line and let me know the output.
thanks

**Comment by mfisher5** [comment]
I'm working with Windows 10, which is the same as my laptop and I don't seem to have any trouble with it in class. But my laptop can't handle the data files, so I'm trying to work off of a desktop with the same OS. `!mkdir`, `cd` and `ls` work, but I can't get other, non-bash related commands to work like `!gunzip`:
![jupyter_troubleshoot](https://cloud.githubusercontent.com/assets/22527689/19446549/2d53aa14-944e-11e6-8dd7-5f31c5b3bf16.png)

**Comment by mfisher5** [comment]
I also tried running `!zgrep`, but that is not working either (??)
![jupyter_troubleshoot2](https://cloud.githubusercontent.com/assets/22527689/19446626/73e0d650-944e-11e6-8674-bff93092cae1.png)

**Comment by sr320** [comment]
I believe it is just the fact zgrep, gunzip etc are not installed on your machine.

I believe on Rhonda's Windows machine `gzip -d` worked for decompressing. (`gunzip` did not)

**Comment by mfisher5** [comment]
`zgrep` etc. seem to work fine as long as I run it on the command line, rather than in Jupyter. Do I have to install it differently to get it to work on Jupyter?  
![jupyter_troubleshoot_commandline](https://cloud.githubusercontent.com/assets/22527689/19447019/78ac11d4-9450-11e6-89ad-a842367eb17c.png)

**Comment by sr320** [comment]
For fun try

```
%%bash
zgrep
```

also 

Type `!which bash` in Jupyter, and `which bash` in the command line and let me know the output.
thanks

**Comment by mfisher5** [comment]
!which bash returns: `/usr/bin/bash`, but the `%%bash zgrep` has been running for about 10 minutes without anything happening...

**Comment by mfisher5** [comment]
when I type in `!which zgrep` into the Jupyter notebook it returns `/usr/bin/zgrep`, if that helps!

**Comment by sr320** [comment]
What is a command you use in command line that works for zgrep?
In other words type

```
%%bash
zgrep yourcommand
```

not just

```
%%bash
zgrep
```
