### ISSUE TITLE
trouble syncing github desktop

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#41]
I dowloaded my project data and made changes to my notebooks in Jupiter, but these changes are not showing up in my Github Desktop. Does this mean that these changes will not show up in my online repository? 

It did show up in my Github Desktop before, but the application kept crashing on my computer when I would try to add files to my .gitignore. I got it to add some files to .gitignore, but it crashed again before I could sync everything. When I opened it now, those changes were not present in the desktop application.

Any way to fix this?

**Comment by yaaminiv** [comment]
I'm also syncing Github Desktop now because I had changes from when we did the in-class blast tutorial that weren't synced. I'm hoping that my other notebook changes will sync as well but I don't think that's likely.

**Comment by sr320** [comment]
First question. 
Please explain how you 

> dowloaded my project data

**Comment by yaaminiv** [comment]
![screen shot 2016-10-14 at 9 18 34 pm](https://cloud.githubusercontent.com/assets/22335838/19407329/ce90f3a2-9253-11e6-81dd-3de0329b3bdd.png)
I used the `!curl` command like we did in class. It worked and I was able to use the `!head` command too.

I also got an error message from Github Desktop, saying there are both local and remote changes to the repository that I have to commit to the master, so I cloned the online repo again and opened it in Github Desktop.

**Comment by sr320** [comment]
For a repository you start in GitHub you have to "Open in Desktop" via GitHub if you want to have the local copy associated with the copy in the cloud.

For example
http://sr320.github.io/course-fish546-2016/01-Notes/#18

Then once you make changes locally, you commit, then sync.

**Comment by sr320** [comment]
If you need a quick work around for tonight.
You can simply save notebook as markdown. 
Then take that text and create a new md file in GitHub, paste, commit.
and use that url.
http://d.pr/i/p6nX

**Comment by yaaminiv** [comment]
I'll use the work around and hopefully figure out the syncing issue this weekend. Thank you!

**Comment by laurahspencer** [comment]
I'm having the same issue -> can't effectively sync the activity on my local GitHub to the cloud. At first the issue was that I had massive files in my repository directory from the Blast tutorial. I deleted those, and the GitHub desktop repository seemed to sync appropriately, but nothing shows up on the cloud. I'll post the .md file contents as a work-around (already tried to post my Jupyter notebook url directly, but I don't think that will work).

**Comment by laurahspencer** [comment]
I couldn't figure out the issue, so I rebuilt my course repository locally then pushed it to GitHub, and now the two seem to communicate.
