### ISSUE TITLE
Repository directory sturcture

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#44]
Please post a screenshot that demonstrates the directory structure of your class repo on your local machine.
Also please confirm your repo is listed correctly @ https://github.com/sr320/course-fish546-2016/wiki (sidebar). If it is incorrect, please edit so it links correctly.

**Comment by hputnam** [comment]
I have another repo as well that will be Jackie's repo https://github.com/hputnam/Montipora_Spawn_Timing
![mcap_tree_junk](https://cloud.githubusercontent.com/assets/5198996/19466769/3655531e-94c2-11e6-98f7-1d971bad8902.jpg)

I am doing the Oly work on RR and will copy over the jupyter notebook(s) and assoc files and push to git when available.

**Comment by sr320** [comment]
My class project repo
![myrepo](http://eagle.fish.washington.edu/cnidarian/skitch/student-fish546-2016_1DB6987A.png)

**Comment by yaaminiv** [comment]
![screen shot 2016-10-18 at 1 43 55 pm](https://cloud.githubusercontent.com/assets/22335838/19495621/fac8cc8c-9538-11e6-8545-7c3a1be533df.png)

**Comment by yaaminiv** [comment]
![screen shot 2016-10-18 at 1 43 55 pm](https://cloud.githubusercontent.com/assets/22335838/19495645/1836f9ce-9539-11e6-8ddf-1235aaa4dd8d.png)

**Comment by mfisher5** [comment]
Sorry for the PC format... 

![repo-structure](https://cloud.githubusercontent.com/assets/22527689/19500138/64d59c5c-954f-11e6-833c-35f846db9d49.jpg)

**Comment by nclowell** [comment]
![screen shot 2016-10-18 at 4 28 34 pm](https://cloud.githubusercontent.com/assets/22554275/19500215/0188823a-9550-11e6-97ed-cb172bf4f593.png)

**Comment by nclowell** [comment]
How do I edit the link to my repo on your sidebar? Is it somewhere in your code and I should start a pull request?

**Comment by sr320** [comment]
@nclowell - I will edit - I thought anyone could, but appears only I can edit. thanks

**Comment by jldimond** [comment]
![screen shot 2016-10-18 at 5 20 30 pm](https://cloud.githubusercontent.com/assets/9869457/19501238/b1f74978-9558-11e6-9c59-f1a60dcb4534.png)

**Comment by nclowell** [comment]
Here's the link to my class repo:

https://github.com/nclowell/FISH546

**Comment by Ellior2** [comment]
Class repo: https://github.com/Ellior2/Fish-546-Bioinformatics

![localdirectory](https://cloud.githubusercontent.com/assets/20071030/19528683/cdfb886c-95e1-11e6-938c-d4194b184af1.PNG)

**Comment by mmiddleton** [comment]
![fish546_directorystructure](https://cloud.githubusercontent.com/assets/22554467/19570677/e6feb900-96af-11e6-8acf-35826e3db5d3.png)

**Comment by aspanjer** [comment]
<img width="739" alt="screen shot 2016-10-21 at 9 38 33 am" src="https://cloud.githubusercontent.com/assets/20097872/19605809/3c7a02dc-9772-11e6-85b3-83ba8e4ab798.png">
<img width="554" alt="screen shot 2016-10-21 at 9 40 00 am" src="https://cloud.githubusercontent.com/assets/20097872/19605832/6189fc62-9772-11e6-8163-d4f751e95677.png">

**Comment by laurahspencer** [comment]
![Spencer Repo. Directory 2016-10-21](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/images/2016-20-21_Repo-Directory.png?raw=true)

**Comment by MeganEDuffy** [comment]
<img width="830" alt="git-repo_2016-10-21" src="https://cloud.githubusercontent.com/assets/13389066/19617342/dc4ca240-97e2-11e6-8844-81e3d34a10d7.png">
