### ISSUE TITLE
trouble running FASTQC in jupyter

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#46]
I tried using `-help` to use FASTQC in jupyter but got this message: 

![message](https://cloud.githubusercontent.com/assets/22335838/19528856/7813bfcc-95e2-11e6-98da-b05fbb9f9b09.png)

I followed the [installation instructions](http://www.bioinformatics.babraham.ac.uk/projects/fastqc/INSTALL.txt) and unzipped the file in my applications folder.

![applications folder](https://cloud.githubusercontent.com/assets/22335838/19528936/d4f4e0d6-95e2-11e6-9125-cbe89bfd937e.png)

Is there something else I missed? I do have the interactive application, but I would like to try using it in the command line.

**Comment by sr320** [comment]
@kubu4 - any experience with this?

**Comment by kubu4** [comment]
That message implies that she should've downloaded this (the link below is the compiled version for OSX):

http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.dmg

**Comment by sr320** [comment]
Correct, but I do not think you can run the compiled version of the command
line.

**Comment by kubu4** [comment]
Oops, sorry, just saw her note below screenshot.

**Comment by kubu4** [comment]
I think she needs to download the Windows/Linux zip file: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip

**Comment by kubu4** [comment]
Also, that wouldn't be the proper command to invoke fastqc.

Fastqc usually installs in the system PATH. To verify this (and see the actual location of Fastqc): `which fastqc`

Be sure to make the proper adjustment for use in a Jupyter notebook (either by preceding command with a `!` or using the bash magic `%%bash` in the cell).

The output from that command should be: `/usr/local/bin/FastQC/fastqc`

**Comment by kubu4** [comment]
Assuming the `which fastqc` command output looks correct, she should just be able to type `fastqc -help`

**Comment by kubu4** [comment]
Now that I've typed all of that out, I'm partly wrong. Do this:
1. Download zip file.
2. Move zip file to /usr/local/bin (`sudo mv fastqc_v0.11.5.zip /usr/local/bin`)
3. Unzip file. (`sudo unzip /usr/local/bin/fastqc_v0.11.5.zip`)
4. Remove .zip file (`sudo rm /usr/local/bin/fastqc_v0.11.5.zip`)
5. Quit Terminal (quit it completely, not just close windows).
6. Start Terminal.
7. Verify installation: `which fastqc`

**Comment by kubu4** [comment]
To add to this, she will need to shutdown her Jupyter notebook before trying this in her Jupyter notebook. Otherwise, Jupyter won't detect the changes to the system (that's why we have to completely shutdown Terminal after the "installation" in the previous post).

**Comment by yaaminiv** [comment]
thanks @kubu4 !

related question: I tried the `!Applications/FastQC/fastqc -help` command after seeing it in one of @sr320's [notebooks](https://github.com/sr320/student-fish546-2016/blob/master/jupyter/00.7-Ostrea-fastqc.ipynb). Why didn't it work in my notebook? Is it just because it wasn't downloaded correctly?

**Comment by kubu4** [comment]
So, @yaaminiv, is it working?

I was distracted when I responding and just realized all the junk I typed up there was totally unnecessary. 

I think the only thing you needed to do to resolve it was just download a different .zip file. Sorry for all the other stuff!

However, putting the files in the location I mentioned above (`/usr/local/bin`) means that you won't have to type the full path to the fastqc; you'll only need to type fastqc.

**Comment by yaaminiv** [comment]
Yes, it worked! I just unzipped the file you suggested and was able to successfully use the `!Applications/FastQC/fastqc -help` command.
![screen shot 2016-10-19 at 8 55 05 pm](https://cloud.githubusercontent.com/assets/22335838/19545826/701602e2-963e-11e6-8db1-3dc963b97458.png)

**Comment by sr320** [comment]
Just to clarify and re-open as other likely will have the same problem
(As the instructions online are very, very bad)

If you are on a Mac and want to use FastQC at the command-line you need to install 
the Windows/Linux zip file: http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip
