### ISSUE TITLE
Readme Completion

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#47]
For your repository, please provide a detailed Readme that includes
- General Description of your project including goals and objectives
- A description of your repository structure, including what each directory includes, and describing any unique files. 
- A projected timeline for what you plan to accomplish in weeks 4 and 5. 

Once you have updated said Readme, add url below.
Feel free to ask for any clarifications, tomorrow during class.

**Comment by mfisher5** [comment]
[updated README.md](https://github.com/mfisher5/mf-fish546-2016/blob/master/README.md)

@sr320  sorry about that! not sure where it went - the link should work now!

**Comment by yaaminiv** [comment]
[updated version](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/README.md)

**Comment by nclowell** [comment]
[updated readme](https://github.com/nclowell/FISH546/blob/master/Cod-Time-Series-Project/README.md)

**Comment by sr320** [comment]
@mfisher5 your link does not work

**Comment by jldimond** [comment]
I'm going to wait to mess with my repo until ipyrad finishes, so I will summarize my goals here (everything else should be in there already):

# **Week** 4

Complete the next ipyrad run and extract data from output. The analysis should finish by Wednesday (I hope).

# **Week** 5

Start to seriously analyze both ddRAD and EpiRAD data, i.e. make some figures. This will include using STRUCTURE to evaluate population subdivision, PCA/MDS for both datasets, and possibly a heat map for the EpiRAD data. The main question is whether I will keep this to strictly hypothesis testing, or do some exploratory analysis of different variables.

**Comment by aspanjer** [comment]
https://github.com/aspanjer/RNAseq_Coho/blob/master/README.md

**Comment by Ellior2** [comment]
[Updated README](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/README.md)

**Comment by laurahspencer** [comment]
[L. Spencer's README 2016-10-21](https://github.com/laurahspencer/546-Bioinformatics/blob/master/README.md)

**Comment by mmiddleton** [comment]
https://github.com/mmiddleton/mmiddleton-fish546/blob/master/Readme.md

**Comment by MeganEDuffy** [comment]
[updated README](https://github.com/MeganEDuffy/FISH-546/blob/master/README.md)
