### ISSUE TITLE
Punchcard

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#48]
Take a screenshot of your class repo punchcard.. and post below

**Comment by sr320** [comment]
![screenshot 2016-10-19 at 6 35 42 pm](https://cloud.githubusercontent.com/assets/4442039/19543273/117521f4-962b-11e6-88b8-527c651900cd.png)

**Comment by Ellior2** [comment]
![capture](https://cloud.githubusercontent.com/assets/20071030/19568425/5f771940-96a6-11e6-8296-f4aed1481fb4.PNG)

**Comment by Ellior2** [comment]
![capture](https://cloud.githubusercontent.com/assets/20071030/19568619/1eb85bde-96a7-11e6-889b-41f2ca1022a8.PNG)

**Comment by nclowell** [comment]
![screen shot 2016-10-20 at 9 36 33 am](https://cloud.githubusercontent.com/assets/22554275/19569012/d5e55d06-96a8-11e6-8ef4-f38bb5e72f3c.png)

**Comment by mfisher5** [comment]
![image](https://cloud.githubusercontent.com/assets/22527689/19569474/baba7906-96aa-11e6-82eb-baecad848df9.png)

**Comment by jldimond** [comment]
<img width="1004" alt="screen shot 2016-10-20 at 9 56 05 am" src="https://cloud.githubusercontent.com/assets/9869457/19569676/82094f50-96ab-11e6-80e7-6ea0eef8e7af.png">

**Comment by MeganEDuffy** [comment]
![punchcard from 2016-10-20](https://github.com/MeganEDuffy/FISH-546/blob/master/images/punchcard_2016-10-20.png)

**Comment by MeganEDuffy** [comment]
![punchcard](https://github.com/MeganEDuffy/FISH-546/blob/master/images/punchcard_2016-10-20.png)

**Comment by mmiddleton** [comment]
![fish546_punchcard](https://cloud.githubusercontent.com/assets/22554467/19570643/bfcf5560-96af-11e6-802e-61cf504f4d5f.png)

**Comment by MeganEDuffy** [comment]
<img width="1210" alt="punchcard_2016-10-20" src="https://cloud.githubusercontent.com/assets/13389066/19571225/1d705ce4-96b2-11e6-8440-497ab6f63ceb.png">

**Comment by yaaminiv** [comment]
![screen shot 2016-10-20 at 11 52 31 am](https://cloud.githubusercontent.com/assets/22335838/19573587/bef3fdb0-96bb-11e6-976d-ba87f04b0f9e.png)

**Comment by aspanjer** [comment]
<img width="1009" alt="screen shot 2016-10-21 at 11 06 52 am" src="https://cloud.githubusercontent.com/assets/20097872/19607409/82990cde-977e-11e6-9844-9dcc499ca75b.png">

**Comment by laurahspencer** [comment]
![L. Spencer's Punchcard 2016-10-21](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/images/2016-10-21_punch%20card.png?raw=true)
