### ISSUE TITLE
using MultiQC in jupyter

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#52]
![screen shot 2016-10-20 at 11 48 16 am](https://cloud.githubusercontent.com/assets/22335838/19573515/69c8af70-96bb-11e6-8087-5fe009b15a3f.png)

I installed MultiQC using `conda install -c bioconda multiqc` in the Terminal and it seemed to have worked. But I can't use it in Jupyter. Is there something I missed?

**Comment by sr320** [comment]
How do you know it worked in terminal?
what was the command? what was your `pwd`

It is likely related to whether mutliqc is in your path. This allows you to merely type the command ie `multiqc` and have your computer know where the program is..

see https://github.com/sr320/course-fish546-2016/issues/29
for how to add programs to your path.

You could also use the absolute path.

More info via [this video](https://uw.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=61943995-45c6-46a2-9976-aadc6f42e43b)

**Comment by yaaminiv** [comment]
I tried the command again, and I guess the download didn't work the first time. I will follow the protocol to get `multiqc` listed in my path.

![screen shot 2016-10-21 at 1 04 44 am](https://cloud.githubusercontent.com/assets/22335838/19591168/7ce3aef6-972a-11e6-80f1-879134815b10.png)

**Comment by sr320** [comment]
Note you do not have to include in your path- this is optional

**Comment by sr320** [comment]
Note you do not have to put it in your path to work. This is optional.

**Comment by yaaminiv** [comment]
solved my multiqc problems! it was installed in a separate folder, `/anaconda/bin` that i was unaware of. i'm assuming this is because i was using a `conda` command. for future reference, is there any way to specify in the command line to install the program in a different folder? would i just redirect the "output" to my desired directory?

**Comment by sr320** [comment]
I would always allow the programs download where the "wish" to be. If you start moving things around this breaks dependancies and paths. 
A good habit to get in would be 
1) installing, 
2) testing in terminal, 
3 then adding to [path so all you have to do is type program name](https://github.com/sr320/course-fish546-2016/issues/29).
