### ISSUE TITLE
Redirecting stacks reporting at command line

### ISSUE THREAD

**Issue by mfisher5** [sr320/course-fish546-2016#55]
Stacks does a lot of reporting directly into the terminal as it runs; since I've started running it from Jupyter, this adds a ton of text to the notebook. I'd like to redirect these reports to a text file, but am not sure how -- the actual output from the program are the files containing all of the sequences for each loci, so I don't want to confuse the program by trying to redirect that output into a single text file, but the reporting in terminal doesn't really qualify as standard error - just progress updates. Is there a simple way to accomplish this?

**Comment by sr320** [comment]
While it is not really errors .. 

`2>` will allow you to write this "progress" to a file.  

example 
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/genefish_1DBACDCF.png" alt="genefish_1DBACDCF.png"/>

**Comment by mfisher5** [comment]
Thanks! One last thing - when I'm running code that takes longer than a few hours jupyter returns an error "Websocket ping timeout", and I can't get the kernel restarted. Is there a way to prevent this, or is it just an error in the code?

**Comment by sr320** [comment]
I have never experienced this.. I run notebooks for weeks....

It seems happen to others, when I google, but am not seeing a clear solution.

You get an error in the notebook itself of the commandline where you launched the notebook?

**Comment by sr320** [comment]
Maybe AV software? do you have that running?
could also try advice here https://github.com/jupyter/notebook/issues/808#issuecomment-167219607

**Comment by mfisher5** [comment]
The notebook looks like it is still running, but the error comes up in the terminal. I sifted through some of the advice on the github page, but am having trouble relating it to what I'm doing... it may have something to do with the fact that I am running the commands in a linux VM on a windows desktop. I'll keep trying and maybe post something!
