### ISSUE TITLE
A gene differentially expressed in sea stars...

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#56]
This week there is only one quiz question!

Identify a gene in your "project" taxa that is similar to a gene differentially expressed in sea stars that have wasting disease.

Show your work in R (including [this image](https://github.com/sr320/eimd-sswd/blob/master/precompiled_wd/deseq2.png) with different color scheme).

drop in a url.

**Comment by aspanjer** [comment]
For this weeks quiz question I re-created the graph using the DESeq2 package in R. The code can be found in my repository: https://github.com/aspanjer/RNAseq_Coho/blob/master/Week4quiz/r-analysis.R

Here's the graph: ![graph](http://eagle.fish.washington.edu/cnidarian/skitch/Rplot_tiff_1DC2564D.png)

In the r-code you can see that I output the table of significantly differentiated genes. I merged this with the Phel_transcriptome.fasta so that I had only significantly differentiated sequences. I blasted these sequence against a custom Oncorhyncus protein database to see which differentially expressed genes were most similar to proteins in the Oncorhyncus species ([results here](https://github.com/aspanjer/RNAseq_Coho/blob/master/Week4quiz/whichgene.txt)). I then used the Phel sequence from the closest match to find a nucleotide sequence that is similar on the NCBI website:

![Blastn result](https://github.com/aspanjer/RNAseq_Coho/blob/master/Week4quiz/blastnresults.png?raw=true)

It looks like contig Phel_Contig_122 is a Calmodulin mRNA that is most similar to accession number BTO74184 in Oncorhynucs species (of which rainbow trout are the most well sequenced).

**Comment by yaaminiv** [comment]
My graph (color: violetred), the [R code](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/tutorials/2016-10-26-DESeq2-Tutorial.R) I used to recreate it

![deseq2-tutorial-plot-violetred](https://cloud.githubusercontent.com/assets/22335838/19790505/9aa2aa8a-9c6d-11e6-8bdc-2585b5038113.jpeg)

I then converted the Phel_transcriptome.fasta file to a .tab file in Galaxy, and merged that file with the Phel_DESlist.tab file in R (you can see the specifics in my R code). I used that merged file as my database and completed the analysis, which was documented in [this notebook](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/tutorials/2016-10-26-DESeq2-Tutorial.R). 

I found that the _O. lurida_ TR20512|c0_gl_il gene is most similar to Phel_contig_5519.

**Comment by laurahspencer** [comment]
I documented the work in my [Jupyter Notebook](https://raw.githubusercontent.com/laurahspencer/546-Bioinformatics/master/2016-10_Geo-Ann-Project/Jupyter-Notebooks/Geoduck%20Annotation%20Project.ipynb).
Using R via Jupyter (after downloading the rpy2 program) I created a diff. expressed .tab file and this graph: 

![R plot](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/images/2016-10-27_Rplot.png?raw=true)

I compared the diff. expressed sea star transcriptome to the geoduck gonad transcriptome. I used Galaxy to reformat the data files, then used blast. There were 31 contig sequences that matched, and 10 with an e-value of 0.0, which are shown here: 

![Top 10 matches](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/images/2016-10-27_Same-Contigs.png?raw=true)

**Comment by jldimond** [comment]
<img width="1088" alt="screen shot 2016-10-27 at 5 27 51 pm" src="https://cloud.githubusercontent.com/assets/9869457/19818374/636b66f0-9d04-11e6-9899-d399643e00f3.png">

I blasted the DEGs against the _Porites astreoides_ transcriptome and came up with these matches:

Phel_contig_13223   isotig11416 97.06   34  1   0   605 638 155 188 3e-08   58.4
Phel_contig_13223   isotig22355 94.44   36  2   0   609 644 176 141 1e-07   56.5
Phel_contig_13223   isotig01879 100.00  30  0   0   608 637 139 110 1e-07   56.5
Phel_contig_13223   isotig14225 100.00  29  0   0   609 637 248 276 4e-07   54.7
Phel_contig_8354 isotig10939    76.81   608 133 6   1601    2204    14  617 4e-91     335

Doing a blastx search of Phel_contig_13223 did not return any matches. However, a blastx search of Phel_contig_8354 returned some matches to the following:

<img width="1291" alt="screen shot 2016-10-28 at 11 57 13 am" src="https://cloud.githubusercontent.com/assets/9869457/19818686/be70eeac-9d05-11e6-8ef9-3b47ef21e92a.png">

**Comment by nclowell** [comment]
Here's the graph in medium sea green:
![seastarhw_plot_seagreen](https://cloud.githubusercontent.com/assets/22554275/19822636/567480a2-9d19-11e6-879b-47e5d5a5d6a4.jpeg)

I blasted the differentially expressed genes to the Atlantic cod transcriptome. One of the highest matches was for an alpha tubulin gene:

![screen shot 2016-10-28 at 2 07 12 pm](https://cloud.githubusercontent.com/assets/22554275/19822666/7d39fb2c-9d19-11e6-9e62-e08f4cdcca7f.png)

I documented my work haphazardly in an R script and on Jupyter notebook. Much of the data manipulation was in Text Wrangler and with a couple python scripts I wrote. My Jupyter Notebook for this hw is [here](https://github.com/nclowell/FISH546/blob/master/Seastar_HW/Seastar%20Homework.ipynb), my R script is [here](https://github.com/nclowell/FISH546/blob/master/Seastar_HW/BLAST_HW.R) and a couple of python scripts and other files can be found in my FISH546 repo [here](https://github.com/nclowell/FISH546).

**Comment by mfisher5** [comment]
I recorded my work in my [BLAST_SeaStarTranscriptome notebook](https://github.com/mfisher5/mf-fish546-2016/blob/master/notebooks/BLAST_SeaStarTranscriptome.ipynb) with the R code and python scripts that I used saved in the [TranscriptomeBLAST folder](https://github.com/mfisher5/mf-fish546-2016/tree/master/TranscriptomeBLAST). 
<br>
Here is the graph of the differentially expressed genes, found with this [R code](https://github.com/mfisher5/mf-fish546-2016/blob/master/TranscriptomeBLAST/DESeq2_rstudio.R): 
![degplot](https://cloud.githubusercontent.com/assets/22527689/19822861/7d749498-9d1a-11e6-8aef-1a2b4911e081.png)
<br>
<br>
I used a combination of [python](https://github.com/mfisher5/mf-fish546-2016/blob/master/TranscriptomeBLAST/generateDEGlist.py) and [R](https://github.com/mfisher5/mf-fish546-2016/blob/master/TranscriptomeBLAST/Merge_DEG_Transcriptome.R) to merge the file containing the differentially expressed genes with the full transcriptome fasta file. 
<br>
I couldn't find Pacific cod transcriptome sequences, so I blasted the entire Atlantic cod transcriptome against the differentially expressed genes. 
<br>
[24 genes aligned](https://github.com/mfisher5/mf-fish546-2016/blob/master/TranscriptomeBLAST/GadusMor_Phel_BLAST.tab) with an e-value below 1E-20. 
<br>
Several genes had evalues of 0.0; one of the genes was for a heat shock protein family A: 
![genefunction](https://cloud.githubusercontent.com/assets/22527689/19822950/f7befcca-9d1a-11e6-88c8-d0e6b66e519e.png)
<br>
This mirrored the description of the aligned Phel contig in the BLAST database.

**Comment by mmiddleton** [comment]
![rseastar_degplot](https://cloud.githubusercontent.com/assets/22554467/19826953/01202856-9d4e-11e6-9a55-33073bf8706d.png)

R code used to create this graph can be found at: https://github.com/mmiddleton/mmiddleton-fish546/blob/master/R_seastar/Week4_exercise.R

After merging the Phel_DEGlist.tab file that was produced from the R analysis with the Phel_transcriptome.fasta file, I blasted that file (Phel_DEGlist.seq.fasta) against a trout genome I found online. I had several hits (found in the `blastn_seastar.txt` or the `blastn_seastar_sorted_by_evalue.txt` on my repo), so I just looked at the ones with an e-value of 0. The one I found the most interesting was Phel_contig_1027 which matched well with a gene called "Transitional endoplasmic reticulum ATPase", also known as "valosin". Here is a picture of the sequence from that particular seastar contig blasted against _Oncorhynchus mykiss_ on the NCBI website showing that it matches closely to valosin:

![ncbi_omykiss_valosin](https://cloud.githubusercontent.com/assets/22554467/19827009/108930c4-9d50-11e6-8b86-bbd8983be5a0.png)

I also wrote a notebook of the steps that I went through for this exercise which can be found here: https://github.com/mmiddleton/mmiddleton-fish546/blob/master/R_seastar/R_seastar_notebook.md

**Comment by Ellior2** [comment]
I used R to find the differentially expressed genes found in _Pycnopodia helianthoides_ sea star by using the DESeq2 package and input file Phel_countdata.txt . Here is my graph:

![image](https://cloud.githubusercontent.com/assets/20071030/19826975/017e223e-9d4f-11e6-9948-307dddd37786.png)

Here is my [R-code](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/data/seastar/seastarR.R). 

Then I took this tab file and after several modifications in Galaxy, I merged it with the full transcriptome to attach the nucleic acid sequences to the contig name. I converted this merged file into a fasta file to use as my database for the blastn that I executed with a _C. gigas_ transcriptome from [here](https://ndownloader.figshare.com/files/1471531).  Here is my [notebook](http://localhost:8888/notebooks/notebooks/seastar/001-Blast_Phel_gigas.ipynb#) documenting the blast and here is my [blast output](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/analyses/seastar/blastoutput1.txt).

There were 5 contig matches with e values of 0.0 when blasted with the _C. gigas_ transcriptome.  One of these (Phel_contig_8899) was matched with genes in other organisms that were associated with tubulin structure which I discovered through the NCBI website.

Additional files related to this quiz can be found in my [repo](https://github.com/Ellior2/Fish-546-Bioinformatics)

**Comment by MeganEDuffy** [comment]
I used R to plot the deferentially expressed genes in sea stars (_Pycnopodia helianthoides _) exhibiting wasting disease vs. healthy. The R script I used is [here](https://github.com/MeganEDuffy/FISH-546/blob/master/tutorials/seastar-tutorial/DESeq.R).

The resulting plot is here:
![DESeq2 plot](https://raw.githubusercontent.com/MeganEDuffy/FISH-546/master/tutorials/seastar-tutorial/data/DEG_virus_ex.png)

I took the tab file output of DESeq2 into Galaxy to merge with the full sea star transcriptome, converting to FASTA format so I could blast against a marine microbial (eukaryotic) metatranscriptome I downloaded [here](http://www.ebi.ac.uk/ena/data/view/PRJEB5205).

I think I have some issues with my metatranscriptome having so many ambiguous nucleotides, but I did get some e-values in the 2e-11 range.  They all matched to mitochondrial genes, as you can see in this [notebook](https://github.com/MeganEDuffy/FISH-546/blob/master/tutorials/seastar-tutorial/04-blast.ipynb). 

All work and data for the project can be found [here](https://github.com/MeganEDuffy/FISH-546/tree/master/tutorials/seastar-tutorial).
