### ISSUE TITLE
Trimming adapter sequences

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#59]
I have several TruSeq Adapter sequences present in my data based off of FastQC sequence duplication analysis results (see [notebook](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-10-19-oly-gonad-OA-FASTQC-results.ipynb) for specifics). Are these adapter sequences something I should trim before doing a BLAST? If so, how should I go about this?

**Comment by sr320** [comment]
Great find.. but you would not do BLAST on sequence reads, but rather assembled contigs. 

Here is a notebook where a trim program was used. the adaptors would be included in the cutadapt file  

https://github.com/sr320/course-btea/blob/master/day-1/01-Geoduck-transcriptome.ipynb

```
!/Applications/bioinfo/trim_galore_zip/trim_galore \
--paired \
--retain_unpaired \
--path_to_cutadapt /Users/sr320/.local/bin/cutadapt \
/Users/sr320/data-genomic/tentacle/Geo_Pool_M_CTTGTA_L006_R2_001.fastq \
/Users/sr320/data-genomic/tentacle/Geo_Pool_M_CTTGTA_L006_R1_001.fastq \
/Users/sr320/data-genomic/tentacle/Geo_Pool_F_GGCTAC_L006_R2_001.fastq \
/Users/sr320/data-genomic/tentacle/Geo_Pool_F_GGCTAC_L006_R1_001.fastq
```

**Comment by yaaminiv** [comment]
I'm looking at the notebook, and I'm not entirely sure what the `--path_to_cutadapt` argument does. It's not included in the help file for `trim_galore`; why is this line included?

**Comment by yaaminiv** [comment]
_Currently working in this [notebook](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/notebooks/2016-10-13-oly-gonad-OA.ipynb)_.

I downloaded `cutadapt` and tried to use it, but ended up with an error.

![screen shot 2016-10-28 at 10 08 53 am](https://cloud.githubusercontent.com/assets/22335838/19815204/a31f0378-9cf6-11e6-8b9d-8d116f3afdd2.png)

Below are several screenshots of my `cutadapt` directory. Is there a different path I need to use? I saw that there was an align file in a different folder within that directory, but setting my path to that folder also gives me an error. 

![screen shot 2016-10-28 at 10 12 35 am](https://cloud.githubusercontent.com/assets/22335838/19815332/3237a308-9cf7-11e6-8a27-5a082b2c0d54.png)
![screen shot 2016-10-28 at 10 12 45 am](https://cloud.githubusercontent.com/assets/22335838/19815335/323e92bc-9cf7-11e6-8bba-ee0ba6e255f9.png)
![screen shot 2016-10-28 at 10 12 51 am](https://cloud.githubusercontent.com/assets/22335838/19815336/32402f1e-9cf7-11e6-883b-605401228360.png)
![screen shot 2016-10-28 at 10 13 00 am](https://cloud.githubusercontent.com/assets/22335838/19815333/323a79d4-9cf7-11e6-8d7e-d356a5815841.png)
![screen shot 2016-10-28 at 10 13 07 am](https://cloud.githubusercontent.com/assets/22335838/19815337/3245de78-9cf7-11e6-80ad-819f0bf33b90.png)
![screen shot 2016-10-28 at 10 13 14 am](https://cloud.githubusercontent.com/assets/22335838/19815334/323b3e1e-9cf7-11e6-9da4-17d78b69d03e.png)
![screen shot 2016-10-28 at 10 13 20 am](https://cloud.githubusercontent.com/assets/22335838/19815339/325c430c-9cf7-11e6-9afd-0c918d9af694.png)
![screen shot 2016-10-28 at 10 13 26 am](https://cloud.githubusercontent.com/assets/22335838/19815338/325a1cd0-9cf7-11e6-9561-bcb4569385c4.png)

**Comment by sr320** [comment]
Short take is always look at the manual for the version of software you are running.
Different versions often have different arguments (in fact that is what happened here.)

Also it would be best to go ahead tackle the 2 steps outlined here 
https://github.com/yaaminiv/yaaminiv-fish546-2016/issues/2

not getting hung up on trimming- can always come back to that later.

**Comment by yaaminiv** [comment]
I looked at the trim galore help page and I think I'm using the right arguments! If the problem is with cutadapt, I'm not entirely sure what it is. I'll table this for now and go ahead with BLAST/Kallisto.

**Comment by sr320** [comment]
You are correct - I was wrong in my interpretation of the problem.

Simplest thing would be to just put it in your PATH. 
But get the other items started and we can revisit.
