### ISSUE TITLE
Privacy and disclosure

### ISSUE THREAD

**Issue by Ellior2** [sr320/course-fish546-2016#6]
I am wondering if anyone has any general concerns over making data you have collected public especially if it may turn into a publication. Are you more interested in documenting methodology so that people can reproduce what you have done rather than actually reporting results? I am in the process of trying to get some of my experiments on Github so that my colleagues and I can discuss and prioritize which samples to analyze. However, I think a key component in this decision making process is having some background knowledge of how these oysters performed throughout the experiment. I'm not sure if I necessarily want to release to the _world_ all of our survival data (and other "eye-opening" data) but how can we more forward without doing so?

**Comment by sr320** [comment]
Great question. 

I will answer this as the Instructor, followed by my personal stance.

As the Instructor for this course, a key part of the learning experience will be making our work public and learning from each other. As the _Instructor_ I am happy to work with anyone to find public data to use for projects, as several persons do not have data or might not be ready to share. 

Personally, as a State employee, funded by Federal tax-payer dollars, and recognizing others can greatly benefit from my lab sharing data (increasing the rate of discovery etc) I choose to make our work open and accessible. 

[some slides on the subject](https://github.com/sr320/talk-CC-OA-2015/blob/master/2015-CC-OAweek.pdf)
