### ISSUE TITLE
Translating pipes into tabs

### ISSUE THREAD

**Issue by Ellior2** [sr320/course-fish546-2016#61]
I'm not able to get this command to work from one of your [notebooks](https://github.com/sr320/course-fish546-2016/blob/master/jupyter-nbs/001-fasta2pie.ipynb)
# Translate pipes to tab so SPID is in separate column for Joining

`!tr '|' "\t" <{dbn}_blast_out.tab> {dbn}_blast_out2.tab`

error: `''' is not recognized as an internal or external command,
operable program or batch file.`
Does it matter if it is a tab file or txt? I tried a few other options I found online but none of them seemed to work.

[Notebook](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/notebooks/classproject/002-BlastingProject2.ipynb)

**Comment by sr320** [comment]
@kubu is it possible this is a Windows issue?

**Comment by sr320** [comment]
Sorry meant @kubu4

**Comment by kubu4** [comment]
Yes, definitely a Windows issue (can tell by the "batch file" part of the error message).

However, the beginning of the error message is very odd (the `''' is not recognized`). Not sure what's happening there.

**Comment by kubu4** [comment]
Admittedly, I'm surprised that any of the bash commands are working. When I was testing this, using a fresh install with Anacaonda3 on Windows 10, no bash commands were recognized. I had to have Git Bash installed AND add Git Bash to the Windows 10 system PATH. After that, I could run bash commands (with a caveat - keep reading).

When I run the `tr` with the exclamation point notation, it fails. However, it fails with an error message that you'd expect (`'tr' is not recognized as an internal or external command,
operable program or batch file.`)

When I run the command using the `%%bash` cell magics command, the command works fine.

Not sure if any of this helps.

**Comment by sr320** [comment]
Correct - That is the instructions they were given via Software Carpentry.
https://github.com/sr320/course-fish546-2016/wiki#the-bash-shell

@Ellior2 try using `%%bash`

So instead of 

```
!tr '|' "\t" <{dbn}_blast_out.tab> {dbn}_blast_out2.tab
```

```
%%bash
tr '|' "\t" <{dbn}_blast_out.tab> {dbn}_blast_out2.tab
```

**Comment by sr320** [comment]
Galaxy is a great solution for this .....

![screenshot 2016-10-28 at 3 33 26 am](https://cloud.githubusercontent.com/assets/4442039/19803774/72dee692-9cbf-11e6-9877-f910234b529e.png)

**Comment by Ellior2** [comment]
Ahhhh yes! I am starting to see that Galaxy is my friend, helpful tool for our quiz as well. Thanks
