### ISSUE TITLE
can't download Phel fasta file for HW

### ISSUE THREAD

**Issue by nclowell** [sr320/course-fish546-2016#65]
I manually downloaded the Phel_countdata.txt file by clicking "raw" on Github and saving the page as a text file. The Phel_transcriptome.fasta is too big to do that so I'm trying to do it from the command line.

I used
`curl https://github.com/sr320/eimd-sswd/blob/master/data/Phel_transcriptome.fasta > /users/natalielowell/Git-repos/FISH546/Seastar-HW/output`

And it spit out
`% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34271    0 34271    0     0  61448      0 --:--:-- --:--:-- --:--:-- 62310`

And the file it saved is a few KB and not right file. Help?

**Comment by sr320** [comment]
You downloaded this webpage
https://github.com/sr320/eimd-sswd/blob/master/data/Phel_transcriptome.fasta

It is VERY confusing as the url does end in `.fasta`

![apge](http://eagle.fish.washington.edu/cnidarian/skitch/eimd-sswd_Phel_transcriptome_fasta_at_master_·_sr320_eimd-sswd_and_git-repos_1DC2B162.png)

The data URL: https://raw.githubusercontent.com/sr320/eimd-sswd/master/data/Phel_transcriptome.fasta

Hint: click `view raw` or Download button

**Comment by nclowell** [comment]
Thanks! I got the url for the page with the fasta from Mary. Although it's unclear how she got it. Maybe a Windows/Mac difference?

**Comment by sr320** [comment]
Hint: click view raw or Download button
