### ISSUE TITLE
git merge conflict

### ISSUE THREAD

**Issue by nclowell** [sr320/course-fish546-2016#66]
I've resolved a few merge conflicts by syncing from the desktop Github, but the current merge conflict won't resolve that way. I can't seem to push or pull from the command line, and cloning from github.com or syncing from the desktop isn't changing anything. Any other ways to resolve merge conflicts?

**Comment by sr320** [comment]
Can you show the error the desktop app is giving you?

And the command line info?

**Comment by nclowell** [comment]
I ended up solving my problem by uploading what I wanted to Github manually and cloning the whole thing back down. But thanks!
