### ISSUE TITLE
blastn error message for quiz

### ISSUE THREAD

**Issue by yaaminiv** [sr320/course-fish546-2016#67]
I was able to create my database of differentially expressed seastar genes and now I have my .fastq datafile to compare it to. I set up the code for a blastn and I'm trying to run it, but I keep getting this error message.

![screen shot 2016-10-27 at 3 56 22 pm](https://cloud.githubusercontent.com/assets/22335838/19788592/21d6a8f4-9c5e-11e6-981b-2f7123855801.png)

I'm not sure how to fix this, or what it's referring to! My notebook can be found [here](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/tutorials/2016-10-26-DESeq2-Tutorial-Part-2.ipynb).

**Comment by sr320** [comment]
You are not blasting a fasta file.
You need to be.
It appears you are blasting a fastq file.
Blast the transcriptome- not raw reads.

**Comment by yaaminiv** [comment]
I'm now trying to convert my .fastq file to a .fasta file in Galaxy but it looks like I don't have enough space to do so.
![screen shot 2016-10-27 at 4 31 45 pm](https://cloud.githubusercontent.com/assets/22335838/19789226/ea5c6d28-9c62-11e6-8b89-a0f4dae0c3ed.png)

Should I just abandon this effort and get a _O. lurida_ .fasta file from somewhere else?

**Comment by sr320** [comment]
please see 
https://github.com/yaaminiv/yaaminiv-fish546-2016/issues/1

😸

**Comment by yaaminiv** [comment]
Thanks! I didn't even get notified that the issue was created, so I didn't see it.

**Comment by sr320** [comment]
Be sure to check https://github.com/settings/notifications
