### ISSUE TITLE
Suggestions for good IGV Software tutorials?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2016#73]
I've downloaded the [IGV software ](http://software.broadinstitute.org/software/igv/home) and am a bit stuck on how to get started using it to view my genome data, specifically to get location data of the subsetted >70k bp contigs along the entire genome; does anyone have suggestions for good tutorials on its use?  Thanks!

**Comment by sr320** [comment]
Can you show us what you have tried to do and show us what is not working?
