### ISSUE TITLE
Project Release

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#75]
For this week you will be shipping your first "release" of you project. 
By Friday midnight, create a release and drop url to said release below.

Most of what I will be looking for I indicated in the reviews. 
It should be very clear what you are doing and where you will be going for the remainder of the quarter.
There should be a clear end goal.

**Comment by sr320** [comment]
https://github.com/sr320/student-fish546-2016/releases/tag/v0.1

**Comment by nclowell** [comment]
[Here's](https://github.com/nclowell/FISH546/releases/tag/v1.0) my release!

**Comment by jldimond** [comment]
[Alrighty, Porites!](https://github.com/jldimond/jldimond-fish546-2016/releases/tag/v1.0)

**Comment by mmiddleton** [comment]
https://github.com/mmiddleton/mmiddleton-fish546/releases/tag/v0.1

**Comment by mfisher5** [comment]
[First project release](https://github.com/mfisher5/mf-fish546-2016/releases/tag/0.1)

**Comment by Ellior2** [comment]
[Project release](https://github.com/Ellior2/Fish-546-Bioinformatics/releases/tag/V1.0)

**Comment by aspanjer** [comment]
https://github.com/aspanjer/RNAseq_Coho/releases/tag/v.1

**Comment by MeganEDuffy** [comment]
My [first release](https://github.com/MeganEDuffy/FISH-546/releases/tag/v0.1)

**Comment by yaaminiv** [comment]
https://github.com/yaaminiv/yaaminiv-fish546-2016/releases/tag/v0-alpha

**Comment by laurahspencer** [comment]
Woops, forgot to post the release here. Glad I checked! 

[Geoduck annotation project pre-release](https://github.com/laurahspencer/546-Bioinformatics/releases/tag/DraftVersion01)
