### ISSUE TITLE
ssh into machine

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#76]
What would be the command you would type in the commandline to log into a machine  (128.43.23.230) assuming you have an account with your github user name as your user name and your password is `fish`. How would you verify you are on that machine?

**Comment by yaaminiv** [comment]
to connect to the ssh:
`$ ssh 128.43.23.230 yaaminiv@somename.remotehost.edu`

i'll then be prompted for my password:
`Password: fish`

verify i'm on that machine:
`$ hostname`

**Comment by Ellior2** [comment]
Connect to Secure Shell (SSH):
`$ ssh Ellior2@128.43.23.230`

I'll be prompted for password:
`Password: fish`

Verification commands:
`$ hostname`  will return your hostname
`$ whoami`     will return your username

**Comment by nclowell** [comment]
Connecting to the machine:
`$ ssh 128.43.23.230 nclowell@nevertrustyourdata.washington.edu`

Returns:
`Password:`

And I'd enter:
`Password: fish`

To find out the host name, I'd use 
`$ hostname` 
And it would return
`nevertrustyourdata.washington.edu`
To find out my username, I'd use
`$ whoami` 
And it would return
`nclowell`

**Comment by laurahspencer** [comment]
_Connect:_
`ssh 128.43.23.230 laurahspencer@host.edu`

_Authenticate:_ 
Password
`fish`

_Verify:_
`hostname` (to confirm where I'm working) 
host.edu
`whoami` (to confirm I'm logged in as correct user)
laurahspencer

**Comment by aspanjer** [comment]
To connect:
`$ ssh aspanjer@128.43.23.230`

Would return: 
`$ Password:`

Enter: 
`fish`

To verify connection, I'd type:
`$ hostname`

**Comment by mfisher5** [comment]
(1) connect: 

`$ ssh 128.43.23.230 mfisher5@somedomain.uw.edu`
<br>

(2) which would prompt password input:
`$ Password:`  `fish`
<br>

(3) verify I am connected: 
`$ hostname`
which should return: `somedomain.uw.edu`

(could also verify which account I am using with `whoami`)
`

**Comment by jldimond** [comment]
`ssh jldimond@128.43.23.230`
Password: `fish`

Verify by checking `hostname` or doing `ls` to look at directory structure.

**Comment by mmiddleton** [comment]
command: `ssh mmiddleton@128.43.23.230`
this prompts for a password, so input: `fish`
to verify that the command/password worked and I successfully logged onto that machine, type: `hostname`

**Comment by MeganEDuffy** [comment]
_To connect:_

```
$ ssh 128.43.23.230 MeganEDuffy@supersecure.uw.edu
```

_This would promt:_

```
$ Password
```

and my input would be `fish`

_To verify I'd logged into the remote machine:_

```
$ hostname
```

which should return:

```
supersecure.uw.edu
```

_To verify my username:_

```
$whoami
```

which would return:

```
MeganEDuffy
```
