### ISSUE TITLE
Use of Hyak Node for Trinity

### ISSUE THREAD

**Issue by aspanjer** [sr320/course-fish546-2016#78]
I meant to ask today in class, but did you get an update the use of your Hyak node? 

I figured out that my assembly was failing due to how I trimmed the reads. I'm trying again in Galaxy but I might be up against their time limits if they impose them. Let me know if Hyak might be an option, and if so, how I can access the resource?

Thanks!

**Comment by sr320** [comment]
Will let you know-
Maybe also try Cyverse again?
