### ISSUE TITLE
Using curl to download files from Google Drive?

### ISSUE THREAD

**Issue by MeganEDuffy** [sr320/course-fish546-2016#80]
Has anyone ever used ```curl``` to get files from a Google Drive folder? 

I tried to create an open, sharable link through GD and then use that url, but I only succeeded in getting the html page as you can see [here](https://github.com/MeganEDuffy/FISH-546/blob/master/notebooks/etnp-data/01-mayer-mgf_download.ipynb).  Has anyone tried this?

**Comment by sr320** [comment]
First step is that it would have to be public.. 
Then not sure it would work -

see also https://github.com/prasmussen/gdrive

see also http://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive

**Comment by MeganEDuffy** [comment]
I thought I actually posted this response, but it was still editing, sorry

The GDrive command has been really helpful, thanks!

**Comment by nabeelpredmac** [comment]
using  authorization token YYYY from developer page and file id XXXX in below command  worked for me 

curl -H "Authorization: Bearer YYYYY" https://www.googleapis.com/drive/v3/files/XXXXX?alt=media -o output_file_name

for detail follow the blog (not by me but following this worked for me )
 https://insynout.blogspot.com/2017/01/secret-how-to-download-large-files-from.html
