### ISSUE TITLE
Examining DNA methylation using CoGe

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#81]
This week we are back to the one question quiz 🍾 

This week we will be going over DNA methylation and how analyze this type of data.
For this week's quiz question, each of you will use CoGe to determine DNA methylation in a single oyster sample. See table be for access to the raw data.

For this question you will need to post a url from your repo (ie md, ipynb) that fully documents your activities in a way that it can reproduced and each aspect is explained.  This includes providing links to data generated, and picture of genome browser showing your data.

Then, once you find a region that is interesting (ie lots of DNA methylation)- use blast to identify a sequence in your taxa of interest that is related.

ID | file
--- | ------
sr320 | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_1_s6_R1.fastq.gz`
yaaminiv | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_2_s6_R1.fastq.gz`
mmiddleton | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_3_s6_R1.fastq.gz`
aspanjer | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_4_s6_R1.fastq.gz`
jldimond | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_5_s6_R1.fastq.gz`
mfisher5 | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_14_s6_R1.fastq.gz`
nclowell | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_15_s6_R1.fastq.gz`
laurahspencer | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_16_s6_R1.fastq.gz`
Ellior2 | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_17_s6_R1.fastq.gz`
MeganEDuffy | `http://owl.fish.washington.edu/nightingales/O_lurida/20160203_mbdseq/zr1394_18_s6_R1.fastq.gz`

---
Hint:
![gif](https://github.com/sr320/student-fish546-2016/blob/master/docs/images/CoGe-Bismark-01.gif?raw=true)

**Comment by mfisher5** [comment]
[DNA methylation notebook](https://github.com/mfisher5/mf-fish546-2016/blob/master/DNA_Methylation/Oyster%20DNA%20Methylation%20Notebook.md)

**Comment by yaaminiv** [comment]
https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/tutorials/COGE-tutorial/2016-11-10-COGE-Tutorial.ipynb

**Comment by nclowell** [comment]
[Natalie's methylation HW notebook](https://github.com/nclowell/FISH546/blob/master/Methylation_HW/Using%20CoGe%20to%20look%20at%20O.%20lurida%20data.ipynb)

**Comment by Ellior2** [comment]
[Methylation_quiz nb](https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/notebooks/methylation_quiz/000-CoGe.ipynb)

**Comment by laurahspencer** [comment]
Laura's [_O. lurida_ methylation experiment notebook](https://github.com/laurahspencer/546-Bioinformatics/blob/master/Ostrea-Methylation/notebooks/DNA%20Methylation%20in%20Ostrea%20Lurida.ipynb)

**Comment by aspanjer** [comment]
https://github.com/aspanjer/RNAseq_Coho/blob/master/jupyter_notebooks/Quiz6.ipynb

**Comment by mmiddleton** [comment]
https://github.com/mmiddleton/mmiddleton-fish546/blob/master/quiz_exercises/Week6_CoGe_oyster/CoGe_oyster_methylation_notebook.md

**Comment by MeganEDuffy** [comment]
Megan's [DNA methylation project](https://github.com/MeganEDuffy/FISH-546/tree/master/tutorials/dnameth-tutorial)

**Comment by jldimond** [comment]
https://github.com/jldimond/jldimond-fish546-2016/blob/Macbook_local/notebooks/Olurida_meth_quiz.ipynb
