### ISSUE TITLE
Getting sequences from CoGe

### ISSUE THREAD

**Issue by aspanjer** [sr320/course-fish546-2016#84]
Once I have ran the analysis in CoGe and can view the methylation data, how can I export sequences in regions of interest in a usable format for blasting? To be specific, I can see how to look at sequences from the reads, but how do I get the genome sequence for a specific section so I'm not blasting a thymine-overrepresented bisulfite short read?

<img width="1253" alt="screen shot 2016-11-10 at 2 28 48 pm" src="https://cloud.githubusercontent.com/assets/20097872/20197027/3bb4a088-a752-11e6-834b-48df792bf24c.png">

**Comment by sr320** [comment]
Imagine you have it. But you activate sequence track and then can select....
