### ISSUE TITLE
Visualize Success

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#88]
For this week I would like everyone to post a single image that best represents the analyses you have done for your class project, to date. 

In addition, please ship another release before the end of the week.  
Your response below will need to formatted such that when I click on your image, I get directed to your release page.

**Comment by yaaminiv** [comment]
[![differentially expressed genes](https://raw.githubusercontent.com/yaaminiv/yaaminiv-fish546-2016/master/analyses/oly_oa_gonad_DESeq2/alltreatments.png)](https://github.com/yaaminiv/yaaminiv-fish546-2016/releases/tag/v1)

(s/o to @nclowell for pointing out my graph looks like a manta ray 😆)

**Comment by laurahspencer** [comment]
[<img src="https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/images/2016-11-17_IGV.png?raw=true">](https://github.com/laurahspencer/546-Bioinformatics/releases/tag/v.1.1)

**Comment by nclowell** [comment]
Unfortunately, I need to get through my whole pipeline on my data before I can come up with a meaningful visual. One of the programs takes forever and I tried to run it overnight, but the kernel paused in Jupyter Notebook _shakes fist_. So I've got very little to show visual-wise for my progress.

If I can get through my pipeline at least on a substantial subset of my data, I'll stick a more meaningful figure here later today. In the meantime, please enjoy this word cloud I made using my custom script for the second major program in the Stacks pipeline, `ustacks`.

[![Alt text](https://cloud.githubusercontent.com/assets/22554275/20442941/9dbd9aae-ad7f-11e6-9410-dfc2fb3dc580.png)](https://github.com/nclowell/FISH546/releases/tag/2.0)

**Comment by mfisher5** [comment]
[![](https://github.com/mfisher5/mf-fish546-2016/blob/0.2/Diagrams/NLoci_ParamTestingStacks.png)](https://github.com/mfisher5/mf-fish546-2016/releases/tag/0.2)

**Comment by mfisher5** [comment]
[![img](https://github.com/mfisher5/mf-fish546-2016/blob/0.2/Diagrams/NLoci_ParamTestingStacks.png?raw=true)](https://github.com/mfisher5/mf-fish546-2016/releases/tag/0.2)

**Comment by aspanjer** [comment]
[![heatmap](https://raw.githubusercontent.com/aspanjer/RNAseq_Coho/master/analysis/Differential%20Expression/figure/heatmapDE.tiff)](https://github.com/aspanjer/RNAseq_Coho/releases/tag/v.2)

**Comment by jldimond** [comment]
These are residuals from a linear model of ddRAD read counts vs. EpiRAD read counts. Each figure is a sample, and methylated loci are the ones on the bottom of each figure. This is the best way I have figure out so far to represent the EpiRAD data that controls for variations in library size and read depth across samples. If I wanted to be even more conservative, I could convert these data to binary or ordinal (e.g. methylated = 1, nonmethylated = 0).

![image](https://cloud.githubusercontent.com/assets/9869457/20452331/13ca3e82-adbc-11e6-9b73-efd2cef48c08.png)

**Comment by mmiddleton** [comment]
I don't really have an image since I've had so many problems trying to get a Bismark analysis running, so here is an image of what I started today that I very much hope will not crash my computer over the weekend:
[![bismark2](https://cloud.githubusercontent.com/assets/22554467/20452390/282c4ba8-adbd-11e6-8712-a6f4c8400194.png)](https://github.com/mmiddleton/mmiddleton-fish546/releases/tag/v0.2)

**Comment by Ellior2** [comment]
Here is a simple Venn Diagram illustrating the number of differentially expressed proteins in oysters reared at 23C and 29C at Day 5 post-settlement. My plan next is to look at protein expression levels between these treatments by looking at peak areas.

[![image](https://cloud.githubusercontent.com/assets/20071030/20453365/473c2ecc-add7-11e6-80f2-f91768e25cb9.png)](https://github.com/Ellior2/Fish-546-Bioinformatics/releases/tag/V2.0)

**Comment by MeganEDuffy** [comment]
Ok, I know I wasn supposed to generate another kind of figure than this Lowest Common Ancestor analysis of de novo sequences peptides - but this is a different sample! (And, my attempts at getting a list to proteins to use in GO analysis haven't worked yet).

[![ETNP LCA](https://raw.githubusercontent.com/MeganEDuffy/FISH-546/master/analyses/2016-11-18-062016_ETNP_129.png)](https://github.com/MeganEDuffy/FISH-546/releases/tag/v0.2)
