### ISSUE TITLE
Notification Check [response requested]

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#9]
I just wanted to ping out to see if everyone gets notified of notifications..

If you could just let me know how you were made aware of this message, if in fact you were 🔔

**Comment by Ellior2** [comment]
Email notification

**Comment by yaaminiv** [comment]
Email

**Comment by laurahspencer** [comment]
Email for me too

**Comment by hputnam** [comment]
:email:

**Comment by MeganEDuffy** [comment]
I get an email notice as well

**Comment by jldimond** [comment]
I just started watching this so did not get a notification.

**Comment by aspanjer** [comment]
Just started watching, so I should get notifications now

**Comment by mmiddleton** [comment]
I also just started watching this so I didn't get a notification, but should now. I noticed this message because I was clicking around and exploring.

**Comment by nclowell** [comment]
I found this by browsing the wiki - I don't think I got an email notification!

**Comment by mfisher5** [comment]
now that I'm watching this I should get notifications!

**Comment by sr320** [comment]
I think we have learned that in order to get notified of new issues- everyone needs to [watch](https://github.com/sr320/course-fish546-2016/subscription) or star this repo...
