### ISSUE TITLE
DAVID GO analysis

### ISSUE THREAD

**Issue by aspanjer** [sr320/course-fish546-2016#90]
Here are the two files I'm using in DAVID with Uniprot IDs, my issue is that few of the IDs are recognized by David. These were derived from blasting against only 'reviewed' uniprot proteins. Any help is appreciated...

Background (~120K IDs): [uniprot_reviewed.txt](https://github.com/sr320/course-fish546-2016/files/595292/uniprot_reviewed.txt)
  
Gene List: [ISvCO_uniCodes.txt](https://github.com/sr320/course-fish546-2016/files/595294/ISvCO_uniCodes.txt)

**Comment by sr320** [comment]
I got 77k once converted some of the IDs-
This is great, you will not get all as not all IDs will have associated
data.

Plenty of info to get data from..

screenshot

http://eagle.fish.washington.edu/cnidarian/skitch/DAVID_Functional_Annotation_Table_-__DAVID__Database_for_Annotation__Visualization__and_Integrated_Discovery__Laboratory_of_Immunopathogenesis_and_Bioinformatics__LIB___National_Institute_of_Allergies_and_Infectious_Diseases__NIAID___Scienc_1DDE46A4.png
