### ISSUE TITLE
Identifying CpG sites/islands in FASTA file?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2016#91]
I'm seeking to identify potential methylation sites (CpG's) in my geoduck genome; although the CpG sites aren't definitive methylation sites, they have potential to be.  I believe [CoGe](https://genomevolution.org/coge/) only has programs to identify methylation in bisulfite treated RNASeq files (FASTQ), and it doesn't allow one to select a FASTA file. CoGe format options are: 
![CoGe format options](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/images/2016-11-17_CoGe-formats.png?raw=true)

Does anyone have suggestions on a program/script to use to identify CpG sites, or possibly "islands", in a genome? Thanks!

**Comment by sr320** [comment]
fuzznuc is a tool that finds motifs (in this case your are looking for all `CG` motifs in your sequence.

I believe Galaxy has this tool, you can run it from the command-line, and there are various other web sites that host it.

ie http://www.bioinformatics.nl/cgi-bin/emboss/fuzznuc

There are several output types, but you might want GFF for browser..

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/EMBOSS__fuzznuc_1DDE4663.png" alt="EMBOSS__fuzznuc_1DDE4663.png"/>

**Comment by laurahspencer** [comment]
Thanks! I've been using Galaxy's online tool (usegalaxy.org), and taking snapshots of the inputs for reproducibility; do you recommend downloading the package and running locally?

**Comment by sr320** [comment]
As long as it is documented, Galaxy is fine
