### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2016#93]
For this week, write a bash script (.sh file) that does something practical to files you are working with for your project. Make sure it has 
- a robust bash header
- variables to be set at the top of the file
- `if` statement
- comments indicating what each part of the script does (using `#`)

And at least one of the following
- _Bash array_
- unix program `basename`
- `find`
- `xargs`
- `make`

Add the script to your course repo, then create a jupyter notebook where you run the script and demonstrate the successful completion of the tasks.

Add the url to the Jupyter notebook below

**Comment by yaaminiv** [comment]
[notebook](https://github.com/yaaminiv/yaaminiv-fish546-2016/blob/master/tutorials/bash-scripting-tutorial/2016-12-01-bash-scripting-tutorial.ipynb)

**Comment by jldimond** [comment]
https://github.com/jldimond/jldimond-fish546-2016/blob/master/notebooks/ipyrad_script.ipynb

**Comment by Ellior2** [comment]
https://github.com/Ellior2/Fish-546-Bioinformatics/blob/master/notebooks/script_quiz/001-Bash_Script.ipynb

**Comment by mfisher5** [comment]
[Bash script notebook](https://github.com/mfisher5/mf-fish546-2016/blob/master/notebooks/Bash%20Shell%20Script%20Practice%20-%20Quiz%207.ipynb)

**Comment by aspanjer** [comment]
https://github.com/aspanjer/RNAseq_Coho/blob/master/jupyter_notebooks/Bash%20Script.ipynb

**Comment by nclowell** [comment]
[bash script notebook](https://github.com/nclowell/FISH546/blob/master/Cod-Time-Series-Project/Notebooks/Bash%20HW.ipynb)

**Comment by mmiddleton** [comment]
https://github.com/mmiddleton/mmiddleton-fish546/blob/master/quiz_exercises/Week9_bashscript/Week9_bashscript_notebook.ipynb

**Comment by MeganEDuffy** [comment]
[bash script notebook](https://github.com/MeganEDuffy/FISH-546/blob/master/notebooks/etnp-data/prokka_dir_script.ipynb)

**Comment by laurahspencer** [comment]
[Laura's Notebook!](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/Jupyter-Notebooks/Quiz_Script.ipynb)
