### ISSUE TITLE
unipept's peptide to protein tool not returning output

### ISSUE THREAD

**Issue by MeganEDuffy** [sr320/course-fish546-2016#96]
I'm trying to use Unipept, a web application designed for metaproteomics/metapeptidomics data analysis. The [Unipept CLI](http://unipept.ugent.be/clidocs) is a set of subcommands that are command line wrappers around the Unipept web services. All of the code is on [GitHub](https://github.com/unipept/unipept-cli).

So far I've used one subcommand, ```unipept pept2lca``` to go from a list of (_de novo_ sequenced) tryptic peptides to a csv file listing the lowest common ancestor taxa of proteins matched to these peptides. This worked fine, as you can see in this [notebook](https://github.com/MeganEDuffy/FISH-546/blob/master/notebooks/etnp-unipept/02-using-unipept.ipynb). 

Now I'm trying another subcommand, ```unipept pept2prot```, that should return the set of UniProt entries containing a given tryptic peptide. Its input, according to this CLI subcommand [description](http://unipept.ugent.be/clidocs/pept2prot), can be a file like the one I'm submitting (text files with one tryptic peptide per line). When I try running this, as you can see in this [notebook](https://github.com/MeganEDuffy/FISH-546/blob/master/notebooks/etnp-unipept/03-pept2prot.ipynb), I get no error or output.

It works fine for *some* individual peptides that actually match to UniProt proteins. But if I input a single peptide that doesn't match, I also get no error or returns. Any advice?

**Comment by sr320** [comment]
What is the most common mistake?

single character 🔥 

You have a space in front of every ID 😄 

this will work..

[062016_ETNP_129_peptides.txt](https://github.com/sr320/course-fish546-2016/files/622346/062016_ETNP_129_peptides.txt)


Bonus! http://d.pr/i/C3LA

**Comment by MeganEDuffy** [comment]
Of course! Wish I'd caught that, but glad that's the problem.

Thanks!
