### ISSUE TITLE
Experience using Bowtie to align reads on personal computer?

### ISSUE THREAD

**Issue by laurahspencer** [sr320/course-fish546-2016#99]
I'm curious if anyone has used their personal computer to execute Bowtie to align RNASeq data to a genome index? Curious if this is feasible in terms of time. 
Thanks!

**Comment by sr320** [comment]
You should use one of the several lab computers - ie genefish.
You could do it on a personal computer, it is feasible.
Presume you are using bowtie, for alignment, to ID SNPs.

**Comment by laurahspencer** [comment]
Thanks! Yep, that's what I'm doing- one step at a time.
FYI It took just over an hour on my computer.
